### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one User -- it returned 2!

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1015]
When we created our unique constraint on the email field we didn't consider that we allow logins using case insensitive usernames and email addresses. We should verify how many case insensitive email address duplicates are in the database and see if we need to create rows in the `accounts.SameUser` table for these users.

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/820/

```
MultipleObjectsReturned: get() returned more than one User -- it returned 2!
(22 additional frame(s) were not displayed)
...
  File "utils/session_checks.py", line 36, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "accounts/views.py", line 89, in login
    response = LoginView.as_view(template_name=template_name, authentication_form=authentication_form)(request)
  File "accounts/modelbackend.py", line 43, in authenticate
    user = User.objects.get(email__iexact=username)

MultipleObjectsReturned: get() returned more than one User -- it returned 2!
```

**Comment by philtgun** [comment]
Create new migration, similar to [this](https://github.com/MTG/freesound/commit/78189137a12f18892331fd51f53c3c8a73326585#diff-8bb6e460bac7a55a676b489191eed711R11), but for case-insensitively-equal emails

**Comment by alastair** [comment]
This query gets the accounts that fall into this case:

    select upper(email), count(*) from auth_user group by upper(email) having count(*) > 1
