### ISSUE TITLE
Bad example in API docs

### ISSUE THREAD

**Issue by andrebola** [MTG/freesound#1019]
Currently the following example from the docs for filtering results by geotag with distance error is not working:

https://.../apiv2/search/text/?filter=geotag:"Intersects(-74.093%2041.042%20-69.347%2044.558)"%20distErr=20

I think it should be 

https://.../apiv2/search/text/?filter=geotag:"Intersects(-74.093%2041.042%20-69.347%2044.558)%20distErr=20"

**Comment by ffont** [comment]
It looks like you're right. Did you try it? If it's right I'd suggest you to directly provide a fix in https://github.com/MTG/freesound/blob/master/apiv2/examples.py#L34

Good catch!

**Comment by andrebola** [comment]
yes, I tried both and the first one doesn't return any sound while the second returns some sounds
