### ISSUE TITLE
RelatedObjectDoesNotExist: User has no profile

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1044]
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/885/

```
RelatedObjectDoesNotExist: User has no profile.
(13 additional frame(s) were not displayed)
...
  File "forum/models.py", line 239, in update_last_post_on_post_delete
    post.author.profile.num_posts = F('num_posts') - 1

RelatedObjectDoesNotExist: User has no profile.
```

**Comment by ffont** [comment]
Happened to me when trying to delete a user.
I guess this should never happen (that the profile does not exist), but maybe we should add some try/except? Not sure what to do.

**Comment by andrebola** [comment]
I think we should create a profile to the users which don't have one

**Comment by ffont** [comment]
Hmm thinking twice about it I don't think this is the problem, all users have a profile. The problem is that I'm trying to delete a post and users' profile was deleted first. It should be delete the last :S.
I'm not sure if this can be controlled. Otherwise the try/except solution can work, but I don't like it a lot.

**Comment by ffont** [comment]
Just to clarify, this is a bug introduced now that we don't use triggers to set num counts, etc.

**Comment by andrebola** [comment]
If I understand correctly this was processed asynchronously using the gm worker. And the code that deletes the user is triggered here: https://github.com/MTG/freesound/blob/1187f882af574ca2b5283c7a985871ced1298c9b/general/management/commands/gm_worker_async_tasks.py#L107-L111

One solution that I see is to define a method like we do for soft delete (`delete_user`) that removes everything related to the user in the right order.  The problem with this solution is that someone could still call the delete method of user and it will raise this exception.


The other option, as @ffont mentioned, is to catch this exception. Note that we already do this for Thread.DoesNotExist:

https://github.com/MTG/freesound/blob/1187f882af574ca2b5283c7a985871ced1298c9b/forum/models.py#L251-L255

**Comment by ffont** [comment]
I'd go for catching the exception in this case and adding a proper comment.
