### ISSUE TITLE
Don't do https/no-www redirects for previews and display files

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1045]
An API user complained that "Access-Control-Allow-Origin" started to happen after we deployed the redirect from HTTP to HTTPS and from www to no-www. This can happen if they use links to previews (and possibly displays) which don't use HTTPS scheme and no-www domain. Preview links returned by the API have correct scheme and domain, but if developers have the links stored somewhere these might be old.

One solution for this is to stop applying the redirects for requests retrieving previews and displays. IN any case we should further investigate this and maybe there is some other thing we could do to avoid the problem.

**Comment by alastair** [comment]
Fixed in https://github.com/MTG/freesound-deploy/commit/0d2571c762e077d9655250e5d27252c56bce772d
