### ISSUE TITLE
Signal non-https image tags as an error

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1054]
If the user right now types

`<img src="http://blah.jpg" />` this will be replaced with `<a href="http://blah.jpg">blah.jpg</a>` because otherwise we get non-secure images in secure pages, which most browsers flag as non-secure.

However, this is done without alerting the user (and also to support the things which are already in the DB).

For new messages we should show an error to the user:

> You are trying to embed an image which is hosted on a non-secure website (http). For security reasons we don't support this in Freesound. Please provide an image link to a secure (https) website

**Comment by alastair** [comment]
I think that we shouldn't disallow this - it's possible that images are only available in http, and the user may be OK with a link. We could have a real-time notification below the text box saying this (or something similar), but don't prevent the user from saving it.

**Comment by ffont** [comment]
I thought we had some sort of notification for this. Anyway, as alastair says we should not throw an error but I agree in showing a warning.

**Comment by alastair** [comment]
@ffont tested this on the forum reply page and it works.
We should verify that it works on all forms that use an `HtmlCleaningCharField`
