### ISSUE TITLE
Always refer to sound previews and other resources by an HTTPS URL in the API

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1067]
We do not redirect requests to `/data` to HTTPS. This is to prevent CORS issues with preflight requests sent by web browsers when trying to load sound data.

This means that if a user accesses the API over http (still allowed), they will also load sound previews over http.
We can change the API to force these URLs to always be https, so even if the client access the API over http, we start forcing more access over https.

Using the logging that we collect about http/https API access, we should verify that the majority of the clients that are accessing via http can also handle https requests.
We should also keep an eye on the ratios of http/https, because this might cause us to shift towards more https access, which is a good thing!

**Comment by ffont** [comment]
Closing this issue as this changed a year ago or so when we moved to k8s infrastructure and are not serving anything over http
