### ISSUE TITLE
TypeError: <User: > is not JSON serializable

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1096]
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/972/

```
TypeError: <User: > is not JSON serializable
(2 additional frame(s) were not displayed)
...
  File "donations/management/commands/check_missing_donations.py", line 103, in handle
    logger.info('Recevied donation (%s)' % json.dumps(donation_data))

TypeError: <User: > is not JSON serializable
```

**Comment by ffont** [comment]
I think this I fixed, it happened while I was testing the management command to sync data from Paypal. I generated some errors and marked them as fixed in Sentry, but I might have missed some. I'll check when sentry is back online :)

**Comment by ffont** [comment]
Closing issue as I could double check that this error is no longer valid.
