### ISSUE TITLE
Disallow using email-like usernames

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1103]
Users sometimes sign up with their email address as username. We should really disallow people to sign up with a "^[^@]+@[^@]+$" username ;)

**Comment by ffont** [comment]
Allowing usernames of the form of an can generate problems like the one see in this issue: https://github.com/mtg/freesound/issues/1102

**Comment by alastair** [comment]
I recommend just blocking "@", any sort of magic to try and discover if something is a valid email address will just cause endless problems.

**Comment by ffont** [comment]
> I recommend just blocking "@", any sort of magic to try and discover if something is a valid email address will just cause endless problems.

But Django already has that implemented right? Can't we reuse the validation from email field and "negate" it?

**Comment by alastair** [comment]
Oh yeah, if we're using that in some places then it seems reasonable to use the reverse too

**Comment by bdejong** [comment]
The fix for this:

https://github.com/MTG/freesound/blob/4da3894e812e38bc4a6f9a3e0617dd0fe43d6c6a/accounts/forms.py#L130

to

`regex=r'^[\w.-]+$',`

I almost did it via in-line editing in github, but then there are no tests for this.....

**Comment by ffont** [comment]
> I almost did it via in-line editing in github, but then there are no tests for this.....

Love it! You need to add a test inline :)

**Comment by philtgun** [comment]
- [ ] Check if django changed validation regex for username field

**Comment by alastair** [comment]
https://github.com/django/django/blob/master/django/contrib/auth/validators.py#L20
