### ISSUE TITLE
Email "change" page has weird title and copy

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1123]
Go to:

https://freesound.org/home/edit/ then click "Change your email address"

the copy on that page reads:

> E-mail reset
> Enter your new e-mail address and your current password in the form below, and we'll e-mail instructions for activation.

That is rather confusing.

**Comment by ffont** [comment]
Do you have any proposal for a new text? Maybe:

> Change your email address
> Enter the new email address and your current password in the form below. We will send you an email to the new address with instructions for activation.

Or completely remove the "We will send you an email to the new address with instructions for activation." sentence?
