### ISSUE TITLE
Users continuously fail to sign up?

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1124]
It looks like there is SOMETHING in the signup flow that makes a lot of people misinterpret when registration has NOT worked. Maybe it is the CAPTCHA error which is displayed at the top of the form rather than in the right location?

<img width="939" src="https://user-images.githubusercontent.com/805269/35947330-4536a504-0c1c-11e8-9903-57767cd2fa0b.png">

So, somehow these people think they signed up correctly, then wait for an activation email and never get one...

**Comment by bdejong** [comment]
It would be great to somehow measure the conversion/funnel from "on signup page" to "successfully signed up".

**Comment by alastair** [comment]
Fixed in #1171 and #1177
