### ISSUE TITLE
Bug/feature: simplify register page

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1171]
Our current register page is too complex and users keep thinking they signed up, wait for the activation email (which they won;t get because the signup failed) and then contacting support to ask for help. Searching for their email address in the DB yields no results.

Potentially we could simplify the register page dramatically:

1. username
2. email (no repeat!)
3. password (no repeat, with "reveal" button!)
4. CAPTCHA
5. [button, Create account] ("By creating an account you agree with our <link>TOS</link>)

This should reduce all errors...

**Comment by bdejong** [comment]
By password reveal I mean something like this:

![eye](https://i.ytimg.com/vi/IW8NHJarjl0/hqdefault.jpg)

**Comment by bdejong** [comment]
( I've heard rumors that "By creating an account you agree with our TOS" is no longer valid under GDPR. )

**Comment by ffont** [comment]
> ( I've heard rumors that "By creating an account you agree with our TOS" is no longer valid under GDPR. )

We know that. We are working with our lawyer so that he tells us what we have to do in our case.
