### ISSUE TITLE
Add missing email types in email preference settings

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1183]
Currently, Freesound users have the option to enable or disable email notifications for the following email types:

- One of my sounds is selected as random sound of the day
- New private message received
- New comment on one of my sounds
- Get a weekly update on all users and tags you follow

Nevertheless, there are some other email types that have not yet been included in this list and that users should be able to turn on/off:

 - Mails asking for donations (Donation request/Donation reminder)
 - New post in threads you're subscribed*
 - A new sound remix was added for one of your sounds**

\* Currently users can turn post in threads notifications on/off per thread, still will be good to add a global option to turn them all off.

** Not sure how this currently works, if we send and email when a remix is added and when it is removed, maybe we should stop sending it when it is removed.

**Comment by philtgun** [comment]
Rgarding second note, yes, we send notifications when remix is both added and removed
https://github.com/MTG/freesound/blob/master/sounds/forms.py#L100~L141

**Comment by philtgun** [comment]
Two things to adress:
- [ ] Amazon returns punycode email domains, they should be processed properly
- [ ] Need to add potion to save bounce data for possible processing and analytics

**Comment by philtgun** [comment]
It would be nice to add an abstraction layer for sending emails that has an email type as input and performs email preference check and also renders the template.
