### ISSUE TITLE
Mark deleted accounts as unable to send email

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1198]
If a user soft-deletes their account and keeps sounds then we rename their account and set their email address to 'deleted_user_x@freesound.org'.
We should mark these email addresses as unable to receive email so that we don't try and send notifications to the account.

**Comment by alastair** [comment]
add `Profile.is_deleted_user` to the `Profile.email_is_valid` method

**Comment by ffont** [comment]
Implemented here https://github.com/MTG/freesound/commit/34cb2e4ed2dc2fe1e0e7b014d9c8bd90176f4e13 (including unit test).
Closing the issue.
