### ISSUE TITLE
Apple Touch Icon

### ISSUE THREAD

**Issue by Superanton** [MTG/freesound#1209]
Could you add a "Apple Touch Icon" to Freesound?

You just have to add a file named "apple-touch-icon.png" to the root (152x152 pixel). 

I already created an icon:
![apple-touch-icon](https://user-images.githubusercontent.com/803655/42175318-51a53eec-7e25-11e8-8d64-8c0828e43797.png)

I could also create a pull request but I first want to get sure that there is not a reason against a touch icon. You could also add icons for Android.

**Comment by bdejong** [comment]
This is the full list of all ios and android required resolutions, actually:

```<!-- iPhone(first generation or 2G), iPhone 3G, iPhone 3GS -->
<link rel="apple-touch-icon" sizes="57x57" href="touch-icon-iphone.png">
<!-- iPad and iPad mini @1x -->
<link rel="apple-touch-icon" sizes="76x76" href="touch-icon-ipad.png">
<!-- iPhone 4, iPhone 4s, iPhone 5, iPhone 5c, iPhone 5s, iPhone 6, iPhone 6s, iPhone 7, iPhone 7s, iPhone8 -->
<link rel="apple-touch-icon" sizes="120x120" href="touch-icon-iphone-retina.png">
<!-- iPad and iPad mini @2x -->
<link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad-retina.png">
<!-- iPad Pro -->
<link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-pro.png">
<!-- iPhone X, iPhone 8 Plus, iPhone 7 Plus, iPhone 6s Plus, iPhone 6 Plus -->
<link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-6-plus.png">
<!-- Android Devices High Resolution -->
<link rel="icon" sizes="192x192" href="icon-hd.png">
<!-- Android Devices Normal Resolution -->
<link rel="icon" sizes="128x128" href="icon.png">
```

**Comment by ffont** [comment]
To have icons for all sizes/os etc you need to have quite a number. I used in the past some online tools to do that and it works perfect. There is no specific reason why we have not done that for Freesound, we should definitely do it. I used a tool like this https://realfavicongenerator.net/
I'd by happy if @Superanton opens a pull request :)

**Comment by ffont** [comment]
Hi @Superanton, I just merged and deployed your PR.
The icon looks good, although I think there are certain cases not covered like when saving site in to the home screen in iOS and probably other stuff. For that more code is needed but I think it is fine how it is for now.

Thanks!

**Comment by Superanton** [comment]
Hi @ffont - Sorry I think there is a mistake. I put the icons in /webroot but they are not available on freesound.org/apple-touch-icon.png for example. So the icons are not working right now. Where do we have to move the files so that they will be available in the webroot?

**Comment by ffont** [comment]
oups, I saw the icon in my bookmarks so I thought it worked, must have been the old favicon.
Now that I looked at it in more detail I see we need to configure nginx to serve the files. Will do it!

**Comment by ffont** [comment]
works now!
