### ISSUE TITLE
Try and prevent email address misspellings on signup

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1214]
After the changes to simplify the registration page (#1171, #1177) we've noticed that we're getting quite a large number of bounces to domain names that look almost but not quite like gmail.com (and other popular domains).
We wonder if this is due to people not typing in their email address twice for confirmation. Bram also commented that he's seeing more support requests from users who don't receive the confirmation mail where he can't find their account (which also sounds like invalid email address).
We've talked a bit about how we could improve this and came up with some ideas:
 * Revert to the two email address fields
 * Show a popup before submit "You are making an account with name [x] and email [y]. [ok?] [change]"
 * Show a notification _after_ submit "You have made an account with name [x] and email [y]. If its incorrect, contact us at support" (still makes support work for Bram)
 * Check domain name of email against a list of "common" domains (hotmail, gmail, yahoo, etc) and see if it's a small edit distance away. If so, show a notification, but still allow the user to continue (This won't pick up spelling mistakes on the local part of the address). Alternatively, we could make them confirm the email address a second time only if we think it's "wrong"

**Comment by ffont** [comment]
hmmm, i think reverting the two email address fields is probably the best (and easiest)...

**Comment by philtgun** [comment]
Yes, I think reverting to confirmation email field would address the problem with full scope at the reasonable cost

**Comment by AxonFlux** [comment]
I was just about to create a new issue on this topic, but saw this active ticket. I get a lot of messages through Zendesk along the lines of "not receiving activation e-mail" and 99% of the time it's because they haven't typed their e-mail address correctly.

Can we bump this ticket up and add a "confirm e-mail" text field on the registration page? That's what the majority of registration pages do on the net. 

Sounds like something relatively easy to implement.

**Comment by alastair** [comment]
OK, I've put this in the list of tasks to do this month, we'll try and get it added in one of the next releases.

**Comment by alastair** [comment]
For now we will restore 2 email fields to the registration form.

Our statistics show about 1500 email bounces a week, we assume that this is mostly due to users who didn't receive an email. We will keep an eye on this number after we release this change and see if this number, and the number of support requests drops.

We also saw that the top 10 email domains in FS account for almost 70% of all accounts. I'm also interested in trying a basic js email validator against these top domains (it's only going to fix the domain, but is worth trying). We could try this option in a few months and compare the bounce rate.
