### ISSUE TITLE
Report amazon SES bounce rate and complaint rate to graylog

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1217]
We should connect to amazon and collect our email bounce and complaint rates and send them to graylog for monitoring.
Make the function to get these values a utility function so that we can check on demand if, for example, we are doing bulk email sending.

**Comment by ffont** [comment]
I merged https://github.com/MTG/freesound/pull/1219/ and tested the command in production. It correctly sends the information to Graylog but it does it in a way which is not very useful to us as contents are not correctly parsed.

The messages should have a format like this:

```Whatever text ({"key": value, "key2": value2})```

The dictionary should be one level (not nested). If done in this way, we'll have the key/values as properties in Graylog and can do plots, etc. This is an example how to do it: https://github.com/MTG/freesound/blob/57a8b64ebdcbfe442276eed4958222e3cee8c22f/donations/management/commands/donations_mails.py#L148-L149

I'm reopening this issue as this should be updated. We should also decide how often we call the function in the cronjob. Once per hour maybe?

**Comment by philtgun** [comment]
I have addressed the comment an opened new pull request #1237. Currently the command is supposed to be run every hour. If this period is changed, the way we calculate short-term stats should be updated - see `AWS_SES_SHORT_BOUNCE_RATE_DATAPOINTS` setting

**Comment by ffont** [comment]
Update deployed, works great now. Thanks @philtgun!
