### ISSUE TITLE
Add mroe information in spam email reports

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1218]
The current comment spam email reads:

> Report for spammer/offensive user XXXXXX
> ----------------------------------------
> Hi there super admin!
> User pachok89 has been reported as a spammer or offensive at least three times by different users.
> Here you have a list of the items that have been marked as bad content:
> 
>     * comment: https://freesound.org/admin/comments/comment/XXXXXX/change/
>     * comment: https://freesound.org/admin/comments/comment/XXXXXX/change/
>     * comment: https://freesound.org/admin/comments/comment/XXXXXX/change/
> 
> If you can confirm this user is a spammer or offensive, please delete him following https://freesound.org/admin/auth/user/XXXXXX/delete/
> If the user is not a spammer or offensive, you can clean the reports by following https://freesound.org/people/XXXXXX/clear_flags/

What would be more useful is:

> Comment spam report for user: https://freesound.org/people/bram/
> Comments by user: https://freesound.org/people/bram/comments_by/
> Clear flags: https://freesound.org/people/bram/clear_flags/
>
> DANGER - Delete user: https://freesound.org/admin/auth/user/XXXXXX/actions/full_delete/

**Comment by ffont** [comment]
Spam emails are not only for comments but can include other types of content (always for the same user). I think what would be even more useful is to include an excerpt of the reported comments/messages/posts in the email itself so in most cases there will be no need to even go to Freesound to make a decision.

Eg:

```
* comment: https://freesound.org/admin/comments/comment/XXXXXX/change/
    "bla bla bla bla ...."
* comment: https://freesound.org/admin/comments/comment/XXXXXX/change/
    "bla bla bla bla ...."
* forum post: https://freesound.org/xxx/
    "bla bla bla bla ...."
```
