### ISSUE TITLE
DataError: value too long for type character varying(200)

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1222]
We should either have a code check against this field that fails validation if it's too long, or increase/remove the char limit. From the sentry report it's not clear what the field is, but looking at the database table it should be obvious which one it is.

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/1141/

```
DataError: value too long for type character varying(200)

(11 additional frame(s) were not displayed)
...
  File "apiv2/views.py", line 1350, in create_apiv2_key
    api_client.save()
  File "apiv2/models.py", line 86, in save
    return super(ApiV2Client, self).save(*args, **kwargs)

DataError: value too long for type character varying(200)

```

**Comment by alastair** [comment]
ApiV2Client.url is a django URLField. This is a CharField with a default limit of 200 (and a specific http url validator).
We use a custom form to allow users to make API clients, which doesn't validate this: https://github.com/MTG/freesound/blob/fb09da014c3aa30b617ed8fd5dbe92961cb3f23e/apiv2/forms.py#L31
This is why we got an error from postgres instead of catching it at the view/form.

We should change this field to text - there is no reason to have a character limit, however we should also ensure that we keep the URLValidator.
Some discussion indicates that a limit of ~2000 might be a good idea, but we could consider putting this limit in code rather than the db structure: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by ffont** [comment]
But I'd say id Django has a limit of 200 in the URL field, this is probably a good enough limit right? To me using a text field and adding a URLValidator sounds more hacky. Maybe adding the limit of 200 in our custom form would be a good solution as well?

**Comment by alastair** [comment]
I think that any solution is fine - if we think that 200 chars is enough for a URL then we should just add this limit in our custom form.

**Comment by ffont** [comment]
I tried to write a test to replicate the issue but I was not able to do it because Django is actually validating the length in the `URLValidator`. This is something that might have changed when we updated Django versions. I'll close the issue because I think it is no longer valid.
