### ISSUE TITLE
Changing email address to existing address in DB does not give error

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1226]
I tried to change my email address to frederic.font@youknowwhat.edu and got:

> E-mail reset email sent
> We've e-mailed you instructions for activating your new e-mail address. You should be receiving it shortly.

This is rather confusing for users who already created a secondary account with their second email address.

**Comment by ffont** [comment]
I see the point, but I think this we changed to avoid giving away information about existing email addresses in the DB... Not sure however, because I did receive the email of your email address reset and I was freaking out... Do you remember any of this @alastair @philtgun @andrebola ?

**Comment by bdejong** [comment]
Auch. That you got an email is pretty bad...

**Comment by alastair** [comment]
Right, I think that the idea was that we shouldn't say anything, but also not send an email in this case.

**Comment by philtgun** [comment]
The code seems to be correct, this needs some further testing
https://github.com/MTG/freesound/blob/1fbb618c6e4cccc1e820f8ecd510ab85ecde94fc/accounts/views.py#L1073-L1079

**Comment by alastair** [comment]
the check isn't great - we should use `lower()` on the email value from the form, and we should really check against the `SameUser` table here too.

**Comment by philtgun** [comment]
> Bram used one which I don't use in Freesound (realized just now)

So this behavior is correct and expected... Case closed?

**Comment by alastair** [comment]
> So this behavior is correct and expected... Case closed?
Yes, I think so, but perhaps the text can be improved. And something added to the email to say "if you didn't perform this step you can ignore it" (and make sure that if a random user tries to click that link that it doesn't actually change the email!, https://github.com/MTG/freesound/blob/1fbb618c6e4cccc1e820f8ecd510ab85ecde94fc/accounts/views.py#L1120-L1127)

> @alastair, why do we need the .lower() if we have iexact? 
Ah, I think you're right that iexact fixes the case of the parameter that you pass in. I guess I was thinking that we had to manually lower-case it to perform the match. Never mind.

**Comment by ffont** [comment]
@alastair that's right, I think we should only perform the email reset if the user is logged in. Email reset are triggered from the user settings page, therefore by users with access to their accounts.

**Comment by ffont** [comment]
In a chat with @alastair, we thought that it would be a good idea to also send an email to the old email address after the update is done (if it's not in the bounce list). In this way we would be warning the user in case the account was hijacked.
