### ISSUE TITLE
NoReverseMatch: Reverse for 'sound' with arguments '(u'blimp66', u'88020 ')' not found. 1 pattern(s) tried: ['peo...

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1242]
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/1179/

```
NoReverseMatch: Reverse for 'sound' with arguments '(u'blimp66', u'88020 ')' not found. 1 pattern(s) tried: ['people/(?P<username>[^//]+)/sounds/(?P<sound_id>\\d+)/$']
(2 additional frame(s) were not displayed)
...
  File "sounds/views.py", line 815, in old_sound_link_redirect
    return __redirect_old_link(request, Sound, "sound")
  File "sounds/views.py", line 807, in __redirect_old_link
    return HttpResponsePermanentRedirect(reverse(url_name, args=[obj.user.username, obj_id]))

NoReverseMatch: Reverse for 'sound' with arguments '(u'blimp66', u'88020 ')' not found. 1 pattern(s) tried: ['people/(?P<username>[^//]+)/sounds/(?P<sound_id>\\d+)/$']
```

**Comment by alastair** [comment]
It looks like it's because of the space after the sound id, but perhaps we have to consider, do we still want the old freesound1 urls? Perhaps it's finally time to retire them

**Comment by ffont** [comment]
I think we have to keep them because there are links in the forum and potentially elsewhere... I guess we should remove space from the regexp so that instead of server error Freesound returns 404 if no valid sound ID is entered?

**Comment by alastair** [comment]
In the case that we want to fix this, we probably need to add another cast to `int()` here: https://github.com/MTG/freesound/blob/4426421d54957b0470afdff4c3aacccae663c7b0/sounds/views.py#L806-L807

**Comment by ffont** [comment]
ah I see, you're right the problem is here. Also `try: ... except ValueError: raise Http404` I guess...
