### ISSUE TITLE
Screen reader support in stars/votes

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1247]
According to a comment at https://blog.freesound.org/?p=892 , screen readers are not able to find out what the rating of a sound is.

This might be possible to be solved using HTML `title` attributes, which already apparently make it possible to vote:
![image](https://user-images.githubusercontent.com/18312/46906139-0921ea00-ceff-11e8-8897-d48b9200268a.png)

The vote-titles can have the current score added and star bars that don't allow voting (your own) can get a title or titles added with the current score.

There might be better alternatives to be found in https://www.w3.org/WAI/tutorials/forms/custom-controls/ - have not read yet.

**Comment by ffont** [comment]
Adding this to the "After new frontend" category as new front end might change this.
