### ISSUE TITLE
Reduce Recaptcha use

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1248]
The use of recaptcha to lower the impact of spam is smart. It is lately in my experience prone to being extremely annoying and broken/slow.

Its use punishes:
spammers (good)
moderators (at least we know what we force users to do)
people trying to get legal clearance for projects they are working on and using sounds for.
People who protect privacy by not having a google account (if you don't have one, you are forced to solve AI teaching image identification tasks).

Solution suggesiton:
- keep track of when the last message was sent. Don't require captcha if the last message was sent more than 10 minutes ago (this also means the very first message you ever send doesn't require it).

**Comment by qubodup** [comment]
PS: I would also not require captcha if user is responding to a message received from the user they are writing to. Probably hard to track

**Comment by qubodup** [comment]
PPS: other possible reasons to trust:
- being whitelisted
- having at least one approved sound upload

**Comment by alastair** [comment]
Can you give an example of the pages where the captcha is causing you (or others?) problems? It sounds like the main page causing problems is message sending.
I agree that we could skip the captcha for trusted users - we've already started using this concept in other places so it shouldn't be much of an issue to extend. We already monitor the number of spam message reports from users, so we would need to extend this to see if messages sent without captcha tend to be reported as more or less spammy.

**Comment by qubodup** [comment]
message sending is the main one. I'm not aware of other places where it disturbs. I haven't used the forum in a while.

Oh I just though of another thing: if the user downloaded a sound by the user they are writing to, we could try to assume that they are writing to ask for attribution terms or something like that and not require captcha. Since Freesound tracks downloads per-user this might be realistic to do without a lot of additional work.

**Comment by ffont** [comment]
Hi, IIRC we don't ask for recaptcha in some of the situations you mention. However we could include more "whitelisted" cases as I also found this problem having to convince Freesound I'm not a robot. I'd say users that uploaded one sound never need recaptcha. Also users that posted more than X.

**Comment by qubodup** [comment]
Another case: in registration, the form misinforms the user of acceptable usernames. Ideally (user forgets to click terms agreement) this form would only ask for captcha once to be successful:
https://github.com/MTG/freesound/issues/1258
