### ISSUE TITLE
Moderation Queue - autoplay a sound when clicking on it

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1249]
User story:
I added 5 sounds by one user to my queue and want to moderate them quickly.

Expected process:

1. In my queue, I click on a sound in the list. The sound plays automatically.
2. After 2 seconds I determine that the description is good and the sounds seems to not contain copyrighted content.
3. I click the next sound, only having to move the mouse slightly down before.

Actual process:
1. In my queue, I click on a sound in the list.
2. I have to move the mouse to the tiny play icon to start playback
3. After 2 seconds I determine that the description is good and the sounds seems to not contain copyrighted content.
4. I have to move the mouse back to the list.
5. I click the next sound.

Notes:
This is a UX streamlining ticket to reduce interruptions when executing the moderator role.

- Do not autoplay the selected first sound when visiting https://freesound.org/tickets/moderation/assigned/myId , only after clicking one sound
- Do not autoplay a sound if more than one sound is selected. This might be useful but is probably much easier on the implementation when avoided.
- Do not autoplay a sound when pressing 'select all' or 'select all other by user'
- Do not try to autoplay if queue is empty

Re-usable code (I permit the code to be considered in the public domain or under CC0 1.0 copyright terms for the purpose of integrating it into this project so no attribution necessary if someone else decides to do so): https://github.com/qubodup/FreesoundSupermod/blob/master/queue.js - searching for thie `AUTOPLAY` constant can be used to find the meaningful chunks of code.

**Comment by qubodup** [comment]
I just checked into freesound today, expecting maybe 50 sounds tops. there are 224 sounds. This feature is crucial for reducing the workload.

My old code is way too complicated but at least digging through it for half an hour refreshed my memory of some things, in particular ids and classes. The following code can be injected, for example in Chrome by pressing F12 and paste-ing it into the "Console" (might have to press esc at some point, might have to enable console first in settings). This won't work any more after reloading the page, so it'll have to be injected again.

```
// get row objects
var rows = $('#assigned-tickets-table-wrapper table#assigned-tickets-table tr')

function StopWaiting() {
    $("#sound_0 a.toggle.play")[0].click();
}

function StartWaiting() {
    console.log("loading");
    var loadCheck = setInterval(function(){
        if ($("#sound_0 a.toggle.play").length){
            console.log("loaded");
            StopWaiting();
            clearInterval(loadCheck);
            console.log("loaded");
        }
    });
}

// sound playback and loading class are controlled by the click event
$(rows).find('td:nth-child(2) a').bind('click', function(){
    StartWaiting();
});
```

Maybe I'll come up with a more practical solution later.

**Comment by ffont** [comment]
Thanks for opening the issue @qubodup and the suggestions. We have a look when we get some time to work on moderation pages again.
