### ISSUE TITLE
Assign moderation sounds faster, sort users by queue size/username

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1250]
Two user stories related to the https://freesound.org/tickets/moderation/ page, where you pick which user's sounds you want to moderate.

### 1. Assign sounds faster
User story: Sometimes, as a moderator I can take on all available sounds for moderation but clicking "assign to me" 10 times costs 15-20seconds* and is an unnecessary distraction. As a moderator, I want a button, that instantly assigns all sounds to me.

_*It could take minutes, if the moderator has not figured out that they can middle-mouse-click or control-click and don't have to wait for the new tabs to completely load._

### 2. Sort users by name
User story: Sometimes as a moderator, I need/want to moderate a specific user, whose name I know. I could use ctrl+f search but being allowed to sort by name would make this more convenient. As a moderator, I want the option to sort users by name

### 3. Sort users by queue size (sounds-to-be-moderated count)
User story: Most of the time, as a moderator, I want to sort users by the number of sounds they submitted for moderation. This has two reasons:

#### A. Moderating 100 sounds by one user is magnitudes easier than moderating 10 sounds by 10 users.

The sounds of the same user in one queue are likely to have the same history, type, metadata quality, making it much easier to make decisions, not requiring to change the mindset (think about the issues that field recordings might have like radio in a cafe vs issues that designed sounds might have like using cc-by sounds without attribution).

This is not always true of course. Recently I had one user with 60 sounds who got lazy writing descriptions midway, but still it was much easier to accept the good chunk and defer with request for revised descriptions the other chunk.

Another recent negative example is a user with >50 sounds, of which I accepted all but one (which was the recording of a ringtone, which was most likely from the standard set of pre-recorded ringtones on a phone). Still, processing one user at the same time made the work much easier.

#### B. Moderators have different availability/mood.

Sometimes I want to do little work but help the moderation team. In such cases I usually assign the user with most sounds to me, hoping I can moderate them with higher efficiency (more sounds moderated over time) as described in A.

Sometimes I am not at all in the mood for listening to repetitive sounds and am willing to spend a little more time in exchange for the work being more interesting - sounds by different users have higher chance of having different nature - or more rewarding - even if I have to handle spam, defer bad metadata or delete illegal sounds, thanks to higher variation, there might be a sound that is a really nice listen.

### Workaround/sample implementation

Using the installation steps described in https://github.com/MTG/freesound/issues/1249 , the following code can be used to restore most of https://github.com/qubodup/FreesoundSupermod/ 's functionality (excluding anything related to local storage - that means remembering your last moderation choice for a specific user):

https://openuserjs.org/scripts/qubodup/Freesound_Moderation_Assigner

This code only affects this page https://freesound.org/tickets/moderation/

**Comment by ffont** [comment]
This functionality is duplicated in issues https://github.com/MTG/freesound/issues/1503 and https://github.com/MTG/freesound/issues/1507.
