### ISSUE TITLE
Suggest correct sound URL on 404 pages with correct ID but wrong username

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1251]
If I remember our conversations correctly, the URL https://freesound.org/people/mistersmith/sounds/443026/ intentionally does not redirect to https://freesound.org/people/qubodup/sounds/443026/ to prevent somebody called mistersmith taking my credit.

I think this is valid but also think that handling typos and username changes is much more useful for users getting attribution and users finding content from Freesound.

I suggest a compromise:

### Sound does not exist

If SoundID 443026 does not exist, then the page should inform the visitor of the possible reasons.

The URL https://freesound.org/people/mistersmith/sounds/443026/ is not available and there is no sound with the ID 443026. This means that the sound has either been deleted or that the link you used is wrong. Perhaps a typo.

### Sound does exist

If SoundID 443026 does exist, then the page should inform the visitor of that fact and inform them of the possible reasons for a different user "owning" it.

The URL https://freesound.org/people/mistersmith/sounds/443026/ is not available.

There is however a sound available with the ID 443026.

This might mean that the link you clicked has an incorrect ID or an incorrect user in the URL.

This could be because the user changed their name, because of a typo or other reasons.

The sound with the ID 443026 available at https://freesound.org/people/qubodup/sounds/443026/

### Notes

Ideally Freesound keeps track of name changes and can redirect (I'm not entirely sure that it does not).

Instead of "or other reasons" one could write "or falsification" but this sounds unnecessarily accusing and negative.

**Comment by ffont** [comment]
Hi @qubodup,
Freesound remember username changes and will redirect if that is the case for a 404. If I recall correctly, for the way 404 is implemented it is not straightforward to add this extra info in the 404 page. I'll assume the redirect in case of username change is a good compromise for now. We might get back to this in the future it the problem seems to become bigger. Thanks!
