### ISSUE TITLE
Typo in the upload portal

### ISSUE THREAD

**Issue by AxonFlux** [MTG/freesound#1252]
I have been notified by a user of a typographical error that needs fixing. When you get round to doing general housekeeping:

>There's a misspelling of the word 'coming' where the page pops up when after uploading a sound:
> 
> "Describe
> 
> No files to describe
> 
> It looks like you have not uploaded any audio files yet or all your files have already been described. 
> Please upload some more files before comming back here :)"_

**Comment by alastair** [comment]
Thanks for the report! I've fixed it and it will be live the next time we make a release.

**Comment by AxonFlux** [comment]
Thanks for the swiftness Alastair.
