### ISSUE TITLE
Registration form incorrectly indicates that "@" is allowed in username

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1258]
**Reproduction steps:**
1. Fill out form at https://freesound.org/home/register/ using "@" in the username

**Expected result**
Since a green 'username is available' message is seen, registration will succeed

**Actual result:**
Registration fails with error message:
This value must contain only letters, digits, underscores, dots, dashes and plus signs.

The main issue with this is that user has to repeat CAPTCHA.

**Notes:**

Registration form shows this before:

![image](https://user-images.githubusercontent.com/18312/49655581-45735180-fa3b-11e8-97aa-bdec231904c1.png)

and after:

![image](https://user-images.githubusercontent.com/18312/49655590-4dcb8c80-fa3b-11e8-9a08-ab0cb75d00b5.png)

**Comment by alastair** [comment]
Good catch - this is because the validation only checks to see if there exists a user in the database with the name that has been typed. We should additionally do our username check here too in order to save time!
