### ISSUE TITLE
Admin-only view on sound flags

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1263]
It would be great to have an admin-view for sound flags as administrating them through emails is rather tedious work that requires a lot of clicks. A very simple page like this would help a lot in speeding up the process:

# Offending

Table with these cells, per row, ordered oldest first

- Date
- Date
- Reporting user (either link to username or email)
- Report (text)
- Link to sound
- Link to uploader of sound
- X (delete, via JS, no confirmation)

# Illegal

Table with these cells, per row, ordered oldest first

- Date
- Reporting user (either link to username or email)
- Report (text)
- Link to sound
- Link to uploader of sound
- X (delete, via JS, no confirmation)

# Other

Table with these cells, per row, ordered oldest first

- Date
- Reporting user (either link to username or email)
- Report (text)
- Link to sound
- Link to uploader of sound
- X (delete, via JS, no confirmation)

**Comment by ffont** [comment]
We could implement this easily using the Django admin I guess?

**Comment by bdejong** [comment]
> We could implement this easily using the Django admin I guess?

I have no idea :-D I would guess that things like javascript-to-delete-things might be more complicated to do in the admin than in just a plain old HTML page

**Comment by ffont** [comment]
It would not be using javascript to delete, but Django admin allows you to select a number of items and then delete them in bulk. I guess that workflow would already be a significant improvement? And adding this tables using the Django admin might be ~20 lines of code (maybe).

**Comment by bdejong** [comment]
True... Perhaps not a bad idea...!

**Comment by bdejong** [comment]
I would say:
– list the ID in the list and make that clickable, clicking on the username is weird
- make the reporting username (if it’s there) clickable to go to the user, make the email address clickable (if it’s there)
- add a clickable "uploader" username
- add a clickable link to the sound
- add the reason in the list, replace newlines with " | " and perhaps trim it to a certain length
- provide one filter on the right-hand side to filter either “offending”, “illegal”, “other”

**Comment by ffont** [comment]
Pending to do:

- Double length of reason summary
- Display sound name instead of sound ID (also truncated)

If we truncate in two places we might need to find the Django util function that does it or implement one ourselves. Hmm wait a sec, maybe we can import that https://github.com/MTG/freesound/blob/fb09da014c3aa30b617ed8fd5dbe92961cb3f23e/general/templatetags/util.py#L35 ?

**Comment by bdejong** [comment]
- https://docs.djangoproject.com/en/dev/ref/templates/builtins/?from=olddocs#truncatechars
- would be nice to be able to sort by the different columns

**Comment by bdejong** [comment]
Aha, another thing to put in the list: the sound.is_explicit flag. That way if people flag things as sexual I can just delete the flag, if the sound i flagged.

**Comment by ffont** [comment]
the `truncatechars` this is a templatetag, I guess it can also be imported as function somehow?

**Comment by bdejong** [comment]
@ffont https://github.com/django/django/blob/master/django/template/defaultfilters.py#L249
