### ISSUE TITLE
sound editing operations check a non-existent permission

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1264]
When checking if a user can edit/delete a sound or a pack, or do some other potentially destructive effect we check if the user is doing it to their own item, or if they have a permission:
https://github.com/MTG/freesound/blob/8d8003bd923b1f25fe66314ec0461a5afedb7ab0/sounds/views.py#L375

However, this permission (`sound.can_change`) doesn't actually exist as an explicit permission. This check will fail for any normal user, and succeed for any admin user by virtue of them being an admin.

We should decide if we want to create this permission (is there a need to allow a user who is not an admin to edit sounds?) or if we should replace this check with an explicit check against the user being an admin.

**Comment by ffont** [comment]
Because there is currently no use case for this (that I'm aware of), I'd simply check for user being admin.

**Comment by alastair** [comment]
ok!

**Comment by ffont** [comment]
Hmm apparently I accidentally closed this!
