### ISSUE TITLE
Adding filter in search resets sorting criteria

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1269]
As reported in https://freesound.org/forum/freesound-project/41317/?page=1#post92500, when adding or removing filters in the search page, the search criteria is lost and set to default. This should not happen.

**Comment by xavierfav** [comment]
A way to fix this would be to keep the sort query parameter unformatted in the search view context and add it in the href of the html links when adding or removing a filter.


In `search/views.py`:
```python
def search(request):
    ...
    sort_unformated = request.GET.get("s", None)
    ...
    sort = search_prepare_sort(sort_unformated, forms.SEARCH_SORT_OPTIONS_WEB)
    ....
    tvars = {
        ...
        'sort': sort,
        'sort_unformated': sort_unformated,
        ...
    }
```

in `search/search.html` and `search/templatetags/facets.html`:
```html
<a href=".?g={{grouping}}&q={{search_query}}&f={{ filter.remove_url }}&s={{sort_unformated}}" ...>
...
```
