### ISSUE TITLE
IntegrityError when deleting sounds in development db

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound#1275]
I want to delete all the sounds from my local development db (_freesound_dev_db-2018-01-12-anonymised.sql.bz2_). From the django shell, I did:
```
Sound.objects.all().delete()
```

I get this error:
```
IntegrityError: new row for relation "accounts_profile" violates check constraint 
"accounts_profile_num_sound_downloads_check" 
DETAIL:  Failing row contains (8182469, 8185877, null, null, null, null, f, f, 0, 0, f, f, t, null, null, f, f, null, f, null, 0, -1).
```

The traceback points to this method when trying to update _num_downloads_.

```python
@receiver(post_delete, sender=Download)
def update_num_downloads_on_delete(**kwargs):
    download = kwargs['instance']
    if download.sound_id:
        Sound.objects.filter(id=download.sound_id).update(num_downloads=F('num_downloads') - 1)
        accounts.models.Profile.objects.filter(user_id=download.user_id).update(
            num_sound_downloads=F('num_sound_downloads') - 1)
```

**Comment by ffont** [comment]
This is because sync errors between the 'num_downloads' field in 'Profile' model and the actual 'Download' objects for that profile. Try running the following command to fix this mismatches and then delete again:
```
python manage.py report_count_statuses
```

Note that this will take considerable time as it has to fix download counts. I don't know how long, but it could be in the range of hours (don't remember now...). If that fixes it, then we should close this issue.

**Comment by alastair** [comment]
What we don't know here is if the download counts were actually in sync. I'd be interesting to try and replicate it. It might be possible that we have a bug here anyway which causes issues when deleting sounds in bulk.

**Comment by xavierfav** [comment]
I ended loading again the development db.
And now I am not able to replicate this bug.

I think it was due to some data that I tried to load from a fixture.
I think we can close the issue, thanks!

**Comment by ffont** [comment]
Thanks @xavierfav!
It can be the case that we still have bugs that "unsync" counts with number of objects (for downloads and other stuff probably), but I'll close this issue as it would be generic anyway.
