### ISSUE TITLE
Download sounds of bookmark category in single zip file

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1290]
> As a user I want to be able to create lists of sounds bookmarked in categories and then download them all together in a single ZIP file similar to when downloading a pack

We can do that with relative ease re-using downloading code for the packs use case: https://github.com/MTG/freesound/blob/4616b3410cd171a7b3ec45ce431b11be878555b3/sounds/views.py#L370-L395

Nevertheless we have to decide how to store these downloads. I guess we should create `BookmarkDownload` and `BookmarkSoundDownload` tables like in the packs case. Or we could decide to not store these downloads in DB for now and wait until we refactor bookmarks into _Collections_. Food for thought...

**Comment by ffont** [comment]
Hi,
This is not a script to download a zip of packs. This is currently not possible. What you could do is use the API to automate downloads. You can check documentation here http://freesound.org/docs/api/

cheers

**Comment by aarora8** [comment]
Thank you, I am now able to download my bookmarked sounds using the freesound API and OAuth2 authentication.
