### ISSUE TITLE
Update stripe checkout API

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1307]
We need to upgrade the Stripe checkout API we use for donations to the new version which supports Strong Customer Authentication (and which will be a requirement for some transactions after new EU directives come into play in September). Changes should be fairly simple.

Here is a migration guide form Stripe docs: https://stripe.com/docs/payments/checkout/migration

Here is an example (legacy) code using JS like we're currently doing: https://stripe.com/docs/checkout#integration-custom
Our code will most likely be very similar to that.

**Comment by andrebola** [comment]
I contacted stripe and this was the reply:

`[...] So I have some documentation here explaining new Checkout, along with the quickstarts for the server-side and the client version: https://stripe.com/docs/payments/checkout I don't think the variable amounts option is available for new Checkout, but it may be something that could be added in the future`

I guess we will have to wait until they add this in the future.

**Comment by andrebola** [comment]
After more discussion, we saw a way of using stripe's python library to have variable amount of donations.

Is important to create the webhook from stripe dashboard, with the following parameters:
URL: https://freesound.org/donations/donation-complete-stripe/
Event types: checkout.session.completed
