### ISSUE TITLE
Forum new post layout

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1316]
Topic field is very short compared to the body, and the label for Body is at the bottom of the field. I think it'd look better at the top or above the field
![Screen Shot 2019-05-14 at 7 09 04 PM](https://user-images.githubusercontent.com/19217/57717543-c7ffdd00-767b-11e9-940c-802f365e32b7.png)

**Comment by ffont** [comment]
Agree with all. However it is also true that some of these layout things we just left them because it will all change *soon* with the new frontend.
