### ISSUE TITLE
Freesound context processors run to get data in the API

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1347]
Our custom context processor at https://github.com/MTG/freesound/blob/1ff73fad71425cb957643dd45617259f897f051e/freesound/context_processor.py runs even when we perform an API query, this means that for every API query we perform 4 SQL queries to retrieve data which isn't shown.
We should check what the request path is in this method and only do the queries if we're not in the API

**Comment by alastair** [comment]
We realised that this only happens when viewing the html of the API, because it's rendering a template. It's not run when getting json from the API, so perhaps isn't as important to remove it from the api url structure

**Comment by ffont** [comment]
I'm closing this issue as it is not really impacting API performance and as alastair says its impact would be even further reduced after #1348.
