### ISSUE TITLE
How to get RSS/Atom feed for contributed sounds?

### ISSUE THREAD

**Issue by brylie** [MTG/freesound#1372]
I would like to syndicate the Freesound content on a personal website. How can I get an RSS or Atom feed for the sounds that I have uploaded?

**Comment by alastair** [comment]
Sorry, we don't have feeds on freesound at the moment, however this is a great idea. We're going to add it to our development schedule and try and get them in some time in the future. Thanks!

**Comment by brylie** [comment]
Thanks! I am learning Django development, and could try contributing this feature, if permissible. Would it be something that could be included in peer review process in the near future?

**Comment by ffont** [comment]
Sure, you're welcome to open a pull request and we'll review it :) In that case make sure that when you do so you include all the relevant context and explanations in the description so it is easier for us to test and evaluate the code.

[Here](https://github.com/MTG/freesound/blob/master/DEVELOPERS.md) are some guidelines for Freesound development that we are compiling. The document is not very complete so far but it might have some useful hints.
