### ISSUE TITLE
Clean up similarity server

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1408]
We should make the following upgrades to the similarity server:

- remove files that refer to components that are no longer used
- audit code to find endpoints that are no longer used by freesound, and remove this code
- audit code to see if some things can be cleaned up to be easier to maintain
- ensure that code is py3-ready
- add tests
- add documentation for remaining methods (perhaps by using docstrings and sphinx? https://stackoverflow.com/questions/12108590/autogenerating-command-documentation-with-twisted-and-sphinx)
- we can probably completely get rid of the "indexing server" functionality as with the new docker setup it should be easy to instantiate a new similarity server to do background indexing

**Comment by ffont** [comment]
We have the idea to replace similarity server by solr functionality, so maybe this will not be applicable in the near future.
