### ISSUE TITLE
Docker deploy

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1415]
Some notes for the final steps we need to do for deployment using docker:

* ~~Determine which registry to publish images to (docker-mtg or dtic)~~ use dtic registry, deploy on dtic stack
* How to publish a service on a specific node (important with solr + similarity indexes on local disk) - use node labels
* Image for nginx with mod_zip
* Blog
* ~~Labs website?~~

**Comment by ffont** [comment]
Closing this issue as this information is no longer useful.
