### ISSUE TITLE
Allow multiple license filters in search

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1418]
Currently you can only select one license type to filter search results. I propose the ability to add more than one, for example, CC0 and CCBY; ignoring CCBY-NC.

OR - just the ability to remove non-commercial results. That would have the same effect

This is a suggestion for the new UI implementation

Cheers 
Sam

**Comment by alastair** [comment]
This could be considered for all of our search facets (license, sample rate, file format, bit depth, etc). Instead of having links, we could have check boxes that you can select - as many as you want, and we do an OR search for all selected items

**Comment by ffont** [comment]
In fact, new interface already suggests to do it this way :)
But this is something we could implement for the current interface and then it will be there for the next interface. Most important changes are on backend I guess.

**Comment by AxonFlux** [comment]
Check-boxes sound like a great idea. That's what I'd normally expect for a search filtering system.
