### ISSUE TITLE
Improve error message when uploading large files

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1419]
When uploading files larger than the limit (which should be 1GB), a "413 Request entity too large" error is returned from the server, but our uploader UI only shows a generic error message like "Something went wrong". This creates confusion. When the response from the server is 413, we should show an error message notifying users the file is too big (and indicating the maximum filesize).

**Comment by alastair** [comment]
I think this error comes from nginx, which means we should edit the error template files in freesound-deploy. In the case that we use the ajax uploader, this error message should be able to be read by the javascript, in which case we can make a nice error message.
Additionally, check if the ajax uploader can see the size of the file _before_ it's uploaded, which would save us an additional step

**Comment by ffont** [comment]
When you click upload I think we tell nginx how big the whole upload it will be, and  nginx responds immediately with 413 if it is too large. So we have to click "upload" but not wait for the upload to fail after X minutes (or hours!). Nevertheless this could be optimized by actively asking before clicking upload (I guess). One thing I also discovered is that when uploading multiple files, the size is added, so the 1GB file size limit is for all files combined.

**Comment by alastair** [comment]
If it's a regular "choose file and click upload" that sends a POST then you're right, we'll immediately get the error message. In this case it will be nginx returning it though, before we get to django, so we'll have to decide how to format this message.
I don't think we will have access to information about this file in javascript, without requesting access to the user's filesystem, which I don't think we can easily do.

In the JS upload, [we can get the file size before uploading](https://w3c.github.io/FileAPI/#attributes-blob). I think the fact that we send all sounds as a single request is an implementation detail. Maybe it won't be too difficult to upload these files one at a time instead, which would improve this workflow.

**Comment by ffont** [comment]
Closing this issue as is was implemented in PR #1421
