### ISSUE TITLE
similarity server: perform save in a background thread

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1450]
When we send a request to the similarity server to save the index, it performs the save process in the server thread, and causes the client to block until the process has finished. If the client has a timeout in place, this connection could time out before the saving process has finished.

We should perform the save in a thread so that we can return to the client immediately. Twisted appears to have support for this: https://twistedmatrix.com/documents/current/core/howto/threading.html

**Comment by ffont** [comment]
This is no longer valid as we're moving this funcitonality to new similarity server.
