### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1494]
The former developer started to implement the search page, but it is not finished yet. Here is a *maybe* non exhaustive list of the things remaining.

- [x] Pages are not prepared for mobile, should we set a minimum width for now so the layout is more under control?
- [x] Similar sounds icon should have hand icon
- [x] Bookmark sound icon should have hand icon
- [x] Empty checkboxes do not appear
- [x] Checkbox labels too separated from checkbox
- [x] "Sort by" options missing
- [x] Sound display textual description color should be darker
- [x] Star icons too much separated (stars should be closer)
- [x] Tag border a bit too dark?
- [x] Missing paginator [example here](https://projects.invisionapp.com/d/main#/console/11781900/257443463/preview)
- [x] Too much spacing between user icon, username and date? (check spacing generally as I see more spacing than in the designs)
- [x] Waveform looks smaller compared to the design?
- [x] In filters section you'll need to add the "related tags" type of filter (note the fading that the designer added) [example here](https://projects.invisionapp.com/d/main#/console/11781900/257443463/preview)
- [x] Missing loop button in sound player
- [x] Play button in sound player has some gray background that should be transparent
- [x] Start browsing text should have more weight
- [x] The cross icon (to remove query) should only appear when something has been typed and should be gray. Also it should appear next to the text. Also hand icon should be shown on hovering and clicking should clear input contents (btw: is this kind of behaviour supposed to be implemented in the template?) [example here](https://projects.invisionapp.com/d/main#/console/11781900/255631838/preview)
- [x] The cursor for typing search terms should appear in the left of the placeholder instead of the middle. See [example here](https://projects.invisionapp.com/d/main#/console/11781900/257441522/preview).
- [x] Hovering tags should change their background to black (invert colors) instead of have the shadow. See [example here](https://projects.invisionapp.com/d/main#/console/11781900/255631838/preview).
- [x] The page navbar (is it called like that?) is supposed to change when you scroll down. The version with the full logo is only shown in the front page when you are at the top ([this one](https://projects.invisionapp.com/d/main#/console/11781900/254102154/preview)). In other pages the navbar shown is the one with the reduced logo (only waveform) and the search bar, and the "donate" and "upload sound" buttons are inverted (no background) ([like here](https://projects.invisionapp.com/d/main#/console/11781900/257443464/preview)). In the search page, the search bar from the navbar is not shown ([like in here](https://projects.invisionapp.com/d/main#/console/11781900/255631838/preview)). EDIT: I've seen this is correctly implemented in the Front page

While reviewing related PR, I found a couple more things to check:

- [x] Missing separator lines above and below the "240 sounds ***** sounds **** sort by dropdown" section
- [x] Also missing line separators between filter facets
- [x] Missing duration filter facet. Example here: https://projects.invisionapp.com/d/main#/console/11781900/255631838/preview

**Comment by GenisDiaz** [comment]
@ffont In the sort by selector, what options do you want there?

**Comment by ffont** [comment]
@GenisDiaz the sort options should be the same as on current Freesound, which you can see in the select dropdown next to the input box https://freesound.org/search/

However there's no need to make the options be the same because in my templates these will be dynamically generated.

**Comment by GenisDiaz** [comment]
there're a couple of options right now as an example, I guess that's enough at the moment

**Comment by GenisDiaz** [comment]
Related tags in the filter section don't have the fading because I've seen it so weird, maybe we can discuss it
