### ISSUE TITLE
Moderation UI - Auto-preview sounds

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1505]
Add feature In the moderation interface that enables autoplay of sounds when clicking on the title in the paginated ticket list (left hand side)

Stop playback of first preview when clicking on different ticket; 
If multiple tickets are selected only auto play first ticket and stop playback when previewing another (play button)

Avoid auto-preview when page is first loaded

**Comment by ffont** [comment]
I think this is pretty much related (if not the same) as this https://github.com/MTG/freesound/issues/1249

**Comment by Headphaze** [comment]
Ahh, yes. I would say that is the same. Although much more detailed!
