### ISSUE TITLE
Moderation UI - Compact website navigation/links

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1506]
The moderation interface should be restyled to move all website navigation to the top of the page in one single row. This will allow for a less cluttered and more spacious interface reducing the amount of page scrolling necessary. 

**I also propose for this change to be made for "assign sounds" page.** 

Here is an example of a page hack that isn't beautiful but is functional:

![Screenshot 2020-11-17 at 11 46 41](https://user-images.githubusercontent.com/14247296/99386562-95671e00-28ca-11eb-91ae-521e9f6ee79a.png)

**Comment by qubodup** [comment]
Glad you like the compact design as well!

If interested, the CSS which I used to achieve above design can be found at https://openuserjs.org/scripts/qubodup/Freesound_Moderation_Helper/source

Feel free to copy as you like.

**Comment by Headphaze** [comment]
Thanks for sharing Iwan

**Comment by ffont** [comment]
Thanks @qubodup!
I did not work on this part because as you'll know we're working on a full redesign and doing this required some nasty hacks which I refused to do hehe Hopefully with the new colours etc is enough. thanks!
