### ISSUE TITLE
Moderation UI - Separation of fresh tickets and deferred tickets

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1508]
The interface needs a separation between deferred tickets and fresh tickets that have not been acted upon. The main reason for this is to prevent accidental approval of deferred sounds which we have seen happen. 

The most ideal way to do this would be to have another tab inside the page/window that will hold sounds when deferred which will not be affected by actions made in the main list. This secondary list can be accessed when needed. 

I understand this is quite a bit of work to implement. So I can propose a workaround or meantime solution:
Highlight sounds in a deferred state and if possible, prevent the "select all" and "select user" options from affecting tickets with a deferred status. 

![deferred ticket](https://user-images.githubusercontent.com/14247296/99389322-c5b0bb80-28ce-11eb-95a2-07e680a76c15.png)

**Comment by ffont** [comment]
Hi, I'm working on this ticket right now. I've already done the highlighting of deferred tickets. I was thinking about the "prevent the "select all" and "select user" options from affecting tickets with a deferred status.". Should we think of a way to also be able to select the deferred ones? Maybe add a checkbox "exclude deferred"? @Headphaze

**Comment by Headphaze** [comment]
That sounds good! Although, it might be better the other way around. By default not including deferred sounds and the checkbox says "include deferred". That would mean that you don't have to click it every time you go to the page.
