### ISSUE TITLE
unable to setup locally because of google drive download access not granted

### ISSUE THREAD

**Issue by amilajack** [MTG/freesound#1518]
I really love the work that has been done on this project and I'd love to contribute! I'm trying to setup the project locally but I haven't yet been granted access to the google drive downloaded. Are there any additional steps required to download the sounds?

Thanks in advance!

**Comment by ffont** [comment]
Hi @amilajack,

Thanks for your message! I got your request to access the file, I'll send you an email so we an continue conversation over there. Closing the issue here :)
