### ISSUE TITLE
tardy moderators list contains duplicates

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1521]
https://freesound.org/tickets/moderation/tardy_moderators_sounds/
https://freesound.org/tickets/moderation/

contain the same tickets multiple times.

It seems to be based on the amount of messages in the ticket. A ticket with 4 messages appears 4 times for example.

If the actual reason is hard to solve/figure out, one could run a remove-duplicates function on the list of tickets before it gets generated.

**Comment by ffont** [comment]
Thanks for reporting!
Should double check this functions: https://github.com/MTG/freesound/blob/7a8a8fc3e6f72dcb9fc275afd26cc2bd847d5523/tickets/views.py#L231
