### ISSUE TITLE
New client library for Common Lisp

### ISSUE THREAD

**Issue by ntrocado** [MTG/freesound#1541]
Hi! I wrote a library in Common Lisp to access the Freesound API.
The repository is here: https://github.com/ntrocado/freesound
It supports OAuth2 and all the resources described in the API documentation.
It might be relevant to add it to the [list of 3rd party libraries](https://freesound.org/docs/api/client_libs.html).
Thanks!

**Comment by ffont** [comment]
Thanks, that looks great :)
I just added it, it will appear online soon.
https://github.com/MTG/freesound/commit/949624854146338f648bc86d2e0c3537e8c62656
Thanks for making the client!!
