### ISSUE TITLE
BW profile page needs to support direct link to list of packs

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1545]
The user profile page has a list of sounds and a tab to show a list of packs. There's no way to link someone to the page so that they see the list of packs. We should make sure that when we click on the tab we update the url, and that if the url is visited with this flag that it changes the view to the packs.
This could be done with a full url or an anchor (http://localhost:8000/people/alastairp/packs or (http://localhost:8000/people/alastairp/#packs)

**Comment by ffont** [comment]
thanks for the comment, I'll look into that. 
This http://localhost:8000/people/alastairp/packs  is already being used and redirects to a search query which shows all packs by the user.

What is shown in the profile page are the "latest" packs only, but I still agree that it would be useful to have a way to link to that. I guess I should update the hash in the URL in real-time as well so the link can be copied form the browser.
