### ISSUE TITLE
Fix typos in username reminder process

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1565]
Quick task for someone... There are typos that needs correcting on the username reminder dialogue for better english readability. I've attached the screenshot below for reference. 

Text currently: 

> _"A username reminder was sent to you email address, please make sure you check both your inbox and your spam folder the our email!"_

Text should read:

A username reminder was sent to [your] email address, please make sure you check both your inbox and ~~your~~ spam folder [for] the ~~our~~ email!

![Screenshot 2021-06-19 at 18 48 21](https://user-images.githubusercontent.com/14247296/122651196-1de2c100-d12f-11eb-912f-92388c252fd7.png)

**Comment by ffont** [comment]
Thanks for reporting @Headphaze. Writing fixed, it will be updated on the website next time we merge something, probably in the next days.

**Comment by Headphaze** [comment]
Amazing. Thanks a lot
