### ISSUE TITLE
Allow multiple license filters in search

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1569]
Currently it's only possible to select one of the three licenses to filter. There needs to be a way to filter out non-commercial licenses whilst showing the rest.

Feedback from this thread: 
[/forum/bug-reports-errors-and-feature-requests/43161](https://freesound.org/forum/bug-reports-errors-and-feature-requests/43161)

cheers

**Comment by qubodup** [comment]
I remember it somehow worked in the pre-2023 UI (not sure if through UI or URL directly, but looks like it's already solved:
![image](https://github.com/MTG/freesound/assets/18312/05e08561-a237-4471-805b-5b87f0642eaf)

Which gives the URL

    freesound.org/search/?advanced=&g=1&only_p=&q=happy&f=%20license:%28%22attribution%22+OR+%22creative+commons+0%22%29&s=&w=
