### ISSUE TITLE
Introduce a character limit in sound comments

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1615]
I've noticed recently that comment threads can be abused since there is no apparent character limit.

e.g. This sound's [most recent comment](https://freesound.org/people/juanto9889/sounds/414860/)

Total characters in comment: 265595 

A reasonable limit would be 4000 or less, which roughly fills the browser height on large laptop display

**Comment by alastair** [comment]
Good suggestion. What do you think the behaviour should be if it's over this limit? Should we silently truncate, silently not add the comment, or just cut it to that limit?

Btw, I've deleted the obvious spam comment so it no longer appears. Example here:
<img width="609" alt="Screen Shot 2022-10-06 at 9 49 31 PM" src="https://user-images.githubusercontent.com/19217/194405617-a2ad38ae-a380-4876-832d-16ed5b342e31.png">

**Comment by Headphaze** [comment]
Hmm, that's a good question. Normally, a website would do this elegantly by counting the characters in the text field and then blocking the ability to post if it's over a certain amount of characters, which prevents the loss of text input. This would be a significant task, but the best way to do it in my opinion. 

Option 2 is the simplified route; we should definitely state in text that character limit. Then truncate the text to the limit. It's unlikely that a genuine user will want to post such a long comment that is not spam, so it's fine to do this silently.

**Comment by alastair** [comment]
> Normally, a website would do this elegantly by counting the characters in the text field and then either blocking the ability to add more text or physically click the post button if it's over a certain amount of characters, which prevents the loss of text input. This would be a significant task, but the best way to do it in my opinion.

In my view this is actually quite an easy task to do and I agree that it's a good way of implementing it. We'll look into it, thanks!

**Comment by ffont** [comment]
Closing the issue as the limit was added.
