### ISSUE TITLE
Replace utils.encryption.create_hash with default_token_generator

### ISSUE THREAD

**Issue by Bomme** [MTG/freesound#1644]
I want to suggest to replace all usages of `utils.encryption.create_hash` where `add_secret=True` with django's [`default_token_generator`](https://github.com/django/django/blob/stable/1.11.x/django/contrib/auth/tokens.py#L84).

This way we could leave all cryptographic things including handling of the `SECRET_KEY` to Django.

What do you think @ffont & @alastair?

### utils.encryption.create_hash:
```python
def create_hash(data, add_secret=True, limit=8):
    import hashlib
    m = hashlib.md5()
    if add_secret:
        m.update(str(data) + settings.SECRET_KEY)
    else:
        m.update(str(data))
    return m.hexdigest()[0:limit]
```

**Comment by alastair** [comment]
This sounds like a good idea to me, anything that allows us to hand off hash/key generation to a trusted 3rd party sounds like the right move.

**Comment by ffont** [comment]
yeah, definitely :) Thanks @Bomme!
