### ISSUE TITLE
Add `is_explicit` to the API response

### ISSUE THREAD

**Issue by obulat** [MTG/freesound#1686]
The Sound model has `is_explicit` field:

https://github.com/MTG/freesound/blob/3919c859dc446e9d4707f5520e019142000c7079/sounds/models.py#L654

But it is not available in the API response:

https://github.com/MTG/freesound/blob/3919c859dc446e9d4707f5520e019142000c7079/apiv2/serializers.py#L43-L46 

At [Openverse](https://github.com/WordPress/openverse), we are planning to improve the way we handle Sensitive content[^1], and it would be really helpful if we could use `is_explicit` information for Freesound audio.

[^1]: Planning Openverse Trust and Safety Work: https://docs.openverse.org/projects/proposals/trust_and_safety/index.html

**Comment by ffont** [comment]
@obulat thanks for opening this issue. The field was definitely missing from the API serializer. I just released an update that adds `is_explicit` as a field. Also note that you can use it in query filters (that was already possible before though). I'll close this issue. Thanks again!

**Comment by obulat** [comment]
Thank you for such a quick response, @ffont !
