### ISSUE TITLE
Password reset page misleading; need to run a search; display error if no match is found

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1690]
When attempting to reset password when not logged in to an account [https://freesound.org/home/password_reset/]

The page will tell the user that an email has been sent even if the email address is wrong. This is misleading because it tells the user that the email they entered was correct and they will then go to check the inbox. So if they typed it wrong, they will ultimately be waiting for an email that will never be sent and then they could try again with the wrong email and go round in circles, eventually having to use the contact form. 

We should run a search of the database for matching email addresses before processing the password reset request. If no match is found then the page should display an error that no email address was found. This is how a normal website would handle 'forgot password' requests.

**Comment by ffont** [comment]
Hi @Headphaze,
Thanks for the comment. 

> We should run a search of the database for matching email addresses before processing the password reset request.

This is indeed how Freesound used to work, but we changed it a couple of years ago because the behaviour you describe would allow an attacker to test for valid email addresses in our database. It seems to be a security recommendation to behave like we're doing it now (even if it can be confusing at times). Maybe @alastair has something more to add?

**Comment by Headphaze** [comment]
Ok, fair enough if it's a security measure. If we want to keep it like this, then at least we should change the text displayed to something a little more accurate and less confusing. 

"If the address you've entered is correct, then you should receive an email with instructions for resetting your password"

You could also add this text as additional part...

"If you don't receive it within several minutes, check your spam folder. Try again making sure the address is typed correctly. If you still have issues then feel free to **contact us** <-[hyperlink to contact form]" 

Thoughts?

**Comment by ffont** [comment]
That sounds good, I could add it to the relevant page in the new UI.

**Comment by ffont** [comment]
Addressed in 57fc9644bdc4c7dfadde84f780683b6b594f3d8f
