### ISSUE TITLE
[2023 UI] Moderation assignment sorting not preserved after assigning user

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1708]
The page where you assign users to moderate forgets the sort setting.

Steps to reproduce:

1. go to https://freesound.org/tickets/moderation/
2. use SORT BY dropdown to change from "days in queue" to "sounds in queue"
3. wait for page to reload (url becomes https://freesound.org/tickets/moderation/?order=new_count )
4. press "assign to me" on random user
5. wait

Expectation:

1. the page I reach has the same sorting as I used before (new count)

Actual result:

1. the page defaults to "Days in queue" (url becomes https://freesound.org/tickets/moderation/ for some reason)

Solution suggestions:
1. Ensure the sort is preserved in the URL and the URL is preserved after assigning a user.
2. Implement storage of user's last used sorting for moderation assignment and if the URL contains no sorting, use the stored moderation sorting setting.

**Comment by ffont** [comment]
Thanks for reporting this issue, I just added support to remember last user preference of the sorting mode.
