### ISSUE TITLE
[long title/name text] small visual CSS word non-breaking issue in moderation - user modal

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1758]
There is a small visual CSS issue with words not breaking in moderation - user modal.

Reproduce via:
1. Click on "unassigned sounds" of a user in https://freesound.org/tickets/moderation/
2. If any sound names are long without spaces, they can break the layout like so:
![broken lines](https://github.com/MTG/freesound/assets/18312/e392c58d-6357-4e67-899b-3175e30262ae)

Selector of the red text element:
#pendingModerationModal > div > div > div > div.modal-body > div > div.v-spacing-4 > div.row > div:nth-child(5) > div.v-spacing-top-2.text-grey > div:nth-child(1) > a:nth-child(1)

To solve this, add the following CSS to this element:

    word-wrap: break-word;

which results in:

![fix](https://github.com/MTG/freesound/assets/18312/201c7ac6-e3c0-4912-96c7-3d745c735431)

**Comment by qubodup** [comment]
Long names on https://freesound.org/tickets/moderation/ can do the same:
![image](https://github.com/MTG/freesound/assets/18312/b5cf2eac-ea3a-49f5-aebc-e091b93ed47b)

**Comment by qubodup** [comment]
Alternative solution: use of ellipsis + HTML `<a alt='full link name'>`

**Comment by qubodup** [comment]
FYI this appears to be an overarching problem that also affects the forum and might affect comments, descriptions.

> ![forum screenshot with overflowing URL text](https://github.com/MTG/freesound/assets/18312/1d6e7db1-70da-4bc0-b060-06a6b5e0129d)
https://freesound.org/forum/legal-help-and-attribution-questions/44640/?page=2#thread

Regarding forums, one common method is during the URL identification step to trim and add "" to the content of the automatically generated "a href" tag. Or just add `overflow-wrap: break-word` ( https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap )

**Comment by ffont** [comment]
Thanks for reporting! I added fixes to the places you suggested and some others. If new ones are spotted, I'll fix them as well :)
