### ISSUE TITLE
Add comma separation for tags in the UI

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1763]
YouTube and any other user created content website I can think of that has a 'tags' or 'keywords' filed, uses the ',' character as a separator but freesound does not.

Here is the upload description form ( https://freesound.org/home/describe/sounds/ ):
![upload description form](https://github.com/MTG/freesound/assets/18312/eb9a91ca-21f7-4fe2-bab2-9c1dbba5a916)
In the screenshot above, I am in the process of writing 'hello'.
If I press ',', nothing happens. No ',' is added but the current word is not confirmed.
If I press spacebar or enter, the tag 'hello is added and the next tag entry starts.

Here is a YouTube Tags field:
![image](https://github.com/MTG/freesound/assets/18312/f81ddc9d-8593-4e93-a448-d303bbbd48d5)
Here is a DeviantArt one:
![image](https://github.com/MTG/freesound/assets/18312/3eeeb0f5-3dfa-49c5-9c81-481daaf2589e)
Here is an OpenClipArt one (accidentally took a screenshot after confirming, unstable site doesn't respond right now, so leaving this for now):
![image](https://github.com/MTG/freesound/assets/18312/80895519-24b4-4604-8f6f-d535ec673ff1)
In all 3 cases, if I press ',' the tag is confirmed and the next tag entry starts.

While the ability to use ' ' inside of tags varies (on some sites, ' ' will end the current tag and start the next), using ',' is most certainly standardized. This means the user experience of freesound is slightly off in a moment of potential high concentration in which the sound designer is focusing on the terms that might be good describers and potentially even looks at the keyboard to type, expecting ',' to do what it always does. This can interrupt the focused work and frustrate if noticed late.

**I'd like to suggest that pressing ',' should confirm and separate tags in the input field**

The most common way to store lists of tags is in newline or comma separated strings (with or without space after comma):
tag1ä
tag2ß
tag3ü

tag4ภาษาไทย,tag5, tag6

If I paste the above into the tag field on freesound, this is the result:
![image](https://github.com/MTG/freesound/assets/18312/afb0f903-d7fd-4992-8edb-d41178c3bc59)

**I'd like to suggest that pasting text that contains ',' should use these as separators**

The text

> Add at least 3 tags, separating them with spaces. Join multi-word tags with dashes. For example: field-recording is a popular tag. Only use letters a-z and numbers 0-9 with no accents or diacritics. Note that you can copy and paste between tag fields.

could be updated to

> Add at least 3 tags, separating them with spaces (and/or commas). Join multi-word tags with dashes. For example: field-recording is a popular tag. Only use letters a-z and numbers 0-9 with no accents or diacritics. Note that you can copy and paste between tag fields.

![diff](https://github.com/MTG/freesound/assets/18312/a8ed10fd-5362-4d33-8c4d-462922b05aaa)

Side note, this text is rather long and could be shrunk to:

> At least 3 tags, separated by spaces (and/or commas), join words with dashes (example: field-recording), only letters (a-z) and numbers (0-9), no accents/diacritics. You can copy/paste between tag fields.

![diff](https://github.com/MTG/freesound/assets/18312/d9085646-7bd1-42d5-910e-da88a49b6f68)

**Comment by ffont** [comment]
In cfb549c137c57aac2844e680d4a962a9ea943fd8 I implemented the idea of using `,` as tags separator.
Still missing:
* Improve help text
* "Consolidate" tags when scrolling down the page to avoid an "unfinished" tag to be skipped when submitting form

**Comment by ffont** [comment]
All fixed in 3cc7695ecb87accdb1fa916f3c9bacd6a7afdf91 and a12439a2f6f1f427360a452b2668bcae6b18f675! Will be merge soon.
