### ISSUE TITLE
Add "Edit sound description" button to tickets for uploaders

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1774]
Whenever a moderator asks a user in a ticket to make changes to the title/tags/description, a substantial number of uploaders doesn't know how to. The path to get there is somewhat cumbersome:
1. Click the normal sized black sound title
2. Click Edit sound description

When it could be reduced to one step.

This is what a ticket looks like for a moderator:
> ![image](https://github.com/MTG/freesound/assets/18312/ac570020-843d-42b5-be08-99b7526093f6)

This is what a ticket looks like for an affected uploader:
> ![image](https://github.com/MTG/freesound/assets/18312/fa3414f9-c2bb-42cf-8be6-ea1b3d239193)

This is my suggested change for an affected uploader:
> ![image](https://github.com/MTG/freesound/assets/18312/08d92010-bef8-4732-934e-4486c2c5f425)

(the edit sound description button was added. It is identical to the one on a sound page:
> ![image](https://github.com/MTG/freesound/assets/18312/87c73c1c-927a-4544-8799-3822cd8352b6)

This would also eliminate the need for an externally image showing how to edit sound details via an ad-loaded 3rd party site or having to manage an additional annotated screenshot hosted on freesound. ( https://github.com/MTG/freesound/issues/1765 )

Here is the code on a sound page (https://github.com/MTG/freesound/blob/e48068ce1758623ae986c73746463855c9c93d6c/templates/sounds/sound.html#L282):

    <a class="no-hover btn-secondary display-inline-block w-100 text-center v-spacing-top-3" href="{% url 'sound-edit' sound.user.username sound.id %}">Edit sound description</a>

This button should be displayed instead of `<div class="v-spacing-top-2 text-grey">
                You do not have permissions to perform any actions.
            </div>` if the following are true:

- The page is viewed by the user who created the sound (`{% if ticket.sender.id == user.id %}` might do the trick)
- The sound is not deleted (`{% if sound is not None %}` might do the trick)
- Perhaps other factors that might prohibit editing need to be excluded. If so, hopefully `{% if sound.processing_state == 'OK' %}` would work, which comes from https://github.com/MTG/freesound/blob/e48068ce1758623ae986c73746463855c9c93d6c/templates/sounds/sound.html#L281

I found these variables on the ticket and sound pages. I don't know if all of them area available on the ticket page.

The affected file is https://github.com/MTG/freesound/blob/master/templates/moderation/ticket.html

I suppose an `else if` that chains the above conditions together should be inserted before https://github.com/MTG/freesound/blob/e48068ce1758623ae986c73746463855c9c93d6c/templates/moderation/ticket.html#L108-L112

**Comment by ffont** [comment]
Thanks for the nice ticket description, I made an implementation in commit a4f5163b485fab4adfdbb107efd8dea1df9e2422 which should work, I'll merge soonish.
