### ISSUE TITLE
unconfirmed tag does not get recorded when editing sound

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#1780]
When for example on https://freesound.org/people/qubodup/sounds/740803/edit/ the user presses the save button without confirming the tag, the tag gets confirmed visually, but this last tag does not get added.

![image](https://github.com/MTG/freesound/assets/18312/700a1892-fffd-4aee-b70e-66d162389965)
![image](https://github.com/MTG/freesound/assets/18312/736ef968-0a0c-4001-b961-50b916ca9747)

If I enter "golden" and do not click anywhere and do not press anything else and instead mousewheel scroll to the save button and click it, this tag will not get recorded.

I've been asking users repeatedly in moderation to add tags because they edit their sound but nothing changes. This might be related.

**Comment by qubodup** [comment]
FYI: this issue does not seem to happen during initial description of uploads. Tested with one sound ( https://freesound.org/people/qubodup/sounds/740871/ ). The word "bass" was included after I wrote it and clicked "save sound description".

This might mean that whatever the process on the upload description form is, could fix it for description forms.

![Freesound_-_Describe_sound_file_-_Google_Chrome_24-06-12_14-42-29_20w](https://github.com/MTG/freesound/assets/18312/eba5ff34-6d0f-4a99-b272-b4528dd2a0bb)
Screenshot looks weird because it's ccs-hacked via https://freesound.org/forum/freesound-project/44648/?page=1#post103076

**Comment by ffont** [comment]
I just fixed this in 2439a2f6f1f427360a452b2668bcae6b18f675, closing the issue. Thanks!
