### ISSUE TITLE
Feature Request - Pack Nesting / Pack Heirarchy

### ISSUE THREAD

**Issue by ShangusBurger** [MTG/freesound#1791]
Howdy!

I'm not sure how feasible or difficult this would be, but I'd love to request the following feature:

Packs that can be nested within other packs, mimicking a folder hierarchy in, for example, a sound library.

My main use case for this feature would be recordings taken at the same time with different microphone setups: I would want them all to be included together, but still want to separate the recordings made with an AKG214 from the recordings made with an Oktava 012.

Rather than Having 2 separate packs:
GSC24 Walla Recording Session - AKG214
GSC24 Walla Recording Session - Oktava012

it would be awesome to have 2 sub-packs within the parent pack:
GSC24 Walla Recording Session
     AKG214
     Oktava012

Another use-case may be wanting to have a Parent Pack for "Travel Field-Recordings", and sub-packs for each state/country the recordings were taken in.

This would also mean:
-Creating functionality for downloading sub-packs only (How would this .zip concat the names of the parent pack and the sub pack, if at all)
-Properly downloading a .zip that maintains the packs' heirarchy from freesound. 
-An update to the UI, possibly a waterfall dropdown, in the "Select a sound pack" portion of the sound editing page.
-It would be especially useful in the batch upload feature on freesound, which would mean having some text-based way to deliniate packs from subpacks, possibly semi-colons (e.g. "GameSoundCon Walla" is a pack, "GameSoundCon Walla; AKG214" is a subpack within GameSoundCon Walla).

The more I describe this, the more complicated it gets! So no worries if this doesn't happen for a while/at all.

Much love, and awesome job,
Shane

**Comment by ffont** [comment]
Hi Shane,
Thanks for opening the issue, this indeed an interesting suggestion. We have the idea to develop a concept of "Collections" which includes this idea of nested sounds, but I'm not yet quite sure how to go about it: https://github.com/MTG/freesound/issues/1029. I'm planning to work on that soon. I don't think we would port the same idea to packs, but Collections might be a better way to achieve what you're trying to do anyways.

**Comment by ShangusBurger** [comment]
Thanks for pointing me to Issue #1029! I do think lots of this functionality would tie into the ideas that are already listed there!
