### ISSUE TITLE
Pure javascript upload 

### ISSUE THREAD

**Issue by ghost** [MTG/freesound#258]
Once the player has been replaced by a html5-friendly one, the upload page is the only one that requires flash (although there is currently a failback html form).
As pure javascript-based cross-browser ajax upload is becoming available, it would be useful to provide an unified experience that includes flash-less browsers

Some pointers:
http://fairviewcomputing.com/blog/2008/10/21/ajax-upload-progress-bars-jquery-django-nginx/
http://www.laurentluce.com/posts/upload-to-django-with-progress-bar-using-ajax-and-jquery/

**Comment by alastair** [comment]
https://github.com/MTG/freesound/pull/734
