### ISSUE TITLE
Unsubscribe and "go to" link in forum posts are too close together

### ISSUE THREAD

**Issue by ghost** [MTG/freesound#377]
Emails look like:

<pre><code>
Thread: "Freesound 2.0"
Post URL: http://freesound.org/forum/freesound-project/2801/42076/

If you wish to stop recieving subscription messages, you can unsubscribe by clicking this link:
http://freesound.org/forum/freesound-project/2801/unsubscribe/
</code></pre>

It would be better to put the unsubscribe lower...

**Comment by alastair** [comment]
Part of email redesigns in new interface

**Comment by philtgun** [comment]
I'll just add more space between the links, and check if there are other email templates that might have similar problem. 

It would also be helpful to also add link to notification preferences page and/or specific unsubscribe links for different type of email messages, but it should be addressed after the redesign

**Comment by ffont** [comment]
> It would also be helpful to also add link to notification preferences page and/or specific unsubscribe links for different type of email messages, but it should be addressed after the redesign.

This is a nice idea. You could open a new issue, set it to "current" milestone and add the label "After the new frontend"
