### ISSUE TITLE
Compact displays a bit, show more "new" results

### ISSUE THREAD

**Issue by ghost** [MTG/freesound#439]
Some users note that there should be more space for the "latest uploaded sounds". They get "lost" too quickly...

One user writes: A bit of compacting...A new sound is only easy to find as long as it remains one of the five most recently uploaded sounds,but by compacting(on the front page)"latest news" to same type-size as "Active forum threads" and moving this over/under Freesound projects will free up space for five more recent uploads. Similar thing on the Sounds page, the 5 "most downloaded sounds" basically never changes. Compacting these as links would allow 10 (there's more variation in 5-10). Moving this under/over "most downloaded packs" would free up space for at least 5 more latest sounds.

Another: well, there are a few things about the FS1, I liked better. At the mo. I feel, that the attention span of an uploaded sound is pretty brisk on the first day and then they disappear into the nirvana. The uploads in the last 48 hours bit on FS1 was better.

**Comment by alastair** [comment]
New design!
