### ISSUE TITLE
Redesign functionalities currently in triggers

### ISSUE THREAD

**Issue by ghost** [MTG/freesound#464]
Triggers cause problems when deleting objects because they often tr to modify the object being deleted

**Comment by ffont** [comment]
Consider reimplementing triggers as django signals

**Comment by ffont** [comment]
Update of num_sounds in user profiles is now carried out in django and not as a trigger.
Current db triggers include downloads count, forum post/thread/last_post and sound ratings.

**Comment by ffont** [comment]
sound.num_comments, user.num_sounds and pack.num_sounds are already handled by django now.
Remaining triggers are for ratings (and computing average rating) and for forum stuff.

**Comment by ffont** [comment]
Related to this one (specifically for the case of downloads): https://github.com/MTG/freesound/issues/913

**Comment by andrebola** [comment]
The following triggers can be deleted after merging the branch [remove-db-triggers](https://github.com/MTG/freesound/tree/remove-db-triggers):

forum_thread_delete
forum_post_delete
forum_post_insert
forum_thread_insert
forum_thread_update

download_post_insert
download_post_delete

rating_post_delete
rating_post_insert
rating_post_update
