### ISSUE TITLE
create badges/points that reward/encourage freesound users for their level of activity 

### ISSUE THREAD

**Issue by darad** [MTG/freesound#537]
We need to come up with a system of rules to create points/badges that resemble the level of activity of each user (uploads, posts, comments, ratings, downloads, etc.). Similar to stackoverflow's point system or foursquare's badges. 

Why we want to do this? For a few reason. One being that we may need to ask from some of the most loyal members of the community to contribute in terms of moderation. We also want to be able to encourage people to upload more and more sounds and provide more descriptions about their sounds. We thing a badge mechanism could create a reward system that's highly motivating.

**Comment by bdejong** [comment]
Closing issue in favour of #784
