### ISSUE TITLE
Be able to search through packs by just searching for pack id

### ISSUE THREAD

**Issue by darad** [MTG/freesound#546]
I want to be able to quickly access a particular pack by just searching the pack id. 

Example:

Pack: http://freesound.org/people/Carlos_Vaquero/packs/9514/

I want to access this pack by just entering 9514 in the search box.

**Comment by ffont** [comment]
Pack search is half-there in the new UI and will be fully added at some point so I'm closing this issue and will open another one for the more generic pack search improvement.
