### ISSUE TITLE
Sounds waiting for moderation can't be deleted

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#550]
When a sound is due to be moderated, it can not be deleted by its owner. A "PAGE NOT FOUND" message appears when using the function via the "edit sound information" page.

This might be intended.

However, the editing interface allows to reach the delete function. Meaning that the UI provides access to a function that does not work.

Please either:
1. Allow deleting your own sound when it is in the moderation queue (please check whether there is a reason why this was not possible before, perhaps allowing this allows other bugs to break things?)
2. Remove the functionality to delete your sound while it's being moderated (ideally with a text in its place explaining why deletion is impossible before moderation).

**Comment by ffont** [comment]
I was unable to reproduce this bug.
I could edit and delete the sound normally when in moderation process.
Are you able to reproduce that bug qubodup?

**Comment by qubodup** [comment]
Cannot reproduce.

Perhaps the reporting user had a connection too slow for the 10s validity of the delete page or there was a different issue.

**Comment by ffont** [comment]
Thanks qubodup!!
