### ISSUE TITLE
Deleting bookmarks has pagination jump

### ISSUE THREAD

**Issue by hector** [MTG/freesound#555]
If you have enough bookmarks so that they are paginated, when you delete a bookmark (using the red cross) the page reloads going back to the first page of your bookmarks. It would be desirable that it reloads on the same page you currently are (or the previous if empty after deleting).

**Comment by ffont** [comment]
The pagination jump is in fact already fixed, but there is a layout problem that should be fixed, bookmark name and info appears below small player, should appear in the same line.
