### ISSUE TITLE
Optimise whitelist_user

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#579]
The main query in whitelist_user is

```
        pending_tickets = Ticket.objects.filter(sender=whitelist_user,
                                                source='new sound') \
                                        .exclude(status=TICKET_STATUS_CLOSED)
```

Neither source or status has an index on it, which makes it slow.
This index should help:
`create index tickets_ticket_sender_id_source4 on tickets_ticket(source,sender_id) where status <> 'closed';`
But it'd probably be better to move source and status into their own tables anyway.

**Comment by ffont** [comment]
Once we include this index, we should try the whitelisting functionality without the thread hack (see https://github.com/MTG/freesound/blob/master/tickets/views.py#L571 and https://github.com/MTG/freesound/blob/master/sounds/management/commands/whitelist_user.py)
