### ISSUE TITLE
Periodic session deletion

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#586]
We store user sessions in the database, but django doesn't expire old sessions. We need to periodically clean the `django_session` table.

**Comment by ffont** [comment]
We can use django's clearsessions command once we upgrade Django.

**Comment by alastair** [comment]
huh. as it turns out, older versions of django have this. It's called "cleanup", instead of clearsessions. 
I've added it to cron, hourly. I'm leaving this ticket open so that we can switch to clearsessions once we upgrade.

**Comment by alastair** [comment]
changed to clearsessions, and added crontab file to freesound-deploy
