### ISSUE TITLE
Use solr for selecting a random sound

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#593]
If we add a `random` field to the solr schema then we can use its random ordering to select our random sounds. This should be significantly faster than the current 500ms that it takes to query the database.
Something like this: http://www.params.me/2011/04/solr-random-results.html

**Comment by alastair** [comment]
There are some really good comments here about doing this in postgres using some approximations: http://stackoverflow.com/questions/8674718/best-way-to-select-random-rows-postgresql

**Comment by andrebola** [comment]
This is very related with #839

**Comment by andrebola** [comment]
Now we create the random sounds querying the database in a cron job, so I think we don't need to use solr.

**Comment by andrebola** [comment]
As we already talked, if we want to get a random sound faster we could user solr or improve the way we do it with postgres.

Here I did a comparison between the different ways to get the number of sounds:
```
freesound=# SELECT reltuples AS ct FROM pg_class WHERE oid = 'sounds_sound'::regclass;
   ct   
--------
 347636
(1 row)

Time: 0.265 ms
freesound=# SELECT count(*) from sounds_sound;
 count  
--------
 351626
(1 row)

Time: 101.880 ms
```

I also tried to get a random sound with solr, here is the result, look at Qtime (in milliseconds):

```
{
  "responseHeader": {
    "status": 0,
    "QTime": 132,
    "params": {
      "fl": "id",
      "sort": "headword_random_2158 asc",
      "indent": "true",
      "q": "*:*",
      "_": "1500449463017",
      "wt": "json",
      "rows": "1"
    }
  },
  "response": {
    "numFound": 347129,
    "start": 0,
    "docs": [
      {
        "id": 43423
      }
    ]
  }
}
```
