### ISSUE TITLE
Edit link on ticket page

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#602]
Hello,

As a moderator, I often ask users to edit their sounds. As in the past, often users would not know how to do this, I include the following text at the end of my edit requests:

"To edit the description: 
1. Follow your sound TITLE link on the right of this ticket page to the sound page. 
2. On the sound page follow the 'Edit sound information' link in the bottom right sidebar."

To make editing less of a burden and teaching how to edit less of a burden, I would like to suggest, that an edit link is included on ticket pages.

This link should only be visible to owners of a sound (or, if there are other roles that are allowed to edit users' sounds, to them as well).

For example, the link could be positioned and look like this:
![example](https://cloud.githubusercontent.com/assets/18312/2552671/bf6e5d96-b69c-11e3-9bde-f51f19783ece.png)
by adding
```
<ul id="sound_links" style="background: none;"><li><a href="SOUNDURL/edit/" class="icon" id="edit_link" title="edit sound">Edit sound information</a></li></ul>
```
( http://pastie.org/8976464 ) at the end of div.sound_list_moderation.

Note: Icon, style and link name from sound page used to remain consistent and not introduce new text/association for an existing action.

**Comment by alastair** [comment]
Thanks for including step by step instructions! Hopefully this is still useful after so long!

**Comment by qubodup** [comment]
Thanks! The link works and looks like this:
![test](https://cloud.githubusercontent.com/assets/18312/12787321/3edabd96-ca95-11e5-85f7-aad154145ff3.png)
