### ISSUE TITLE
Bump sounds with user response in moderator's queue

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#605]
Freesound is growing every day and many users are asked to update their information, possibly because there is no solution to https://github.com/MTG/freesound/pull/529 . Moderators are informed of updated tickets via email, which is tedious to click through.

Currently, a moderator's queue shows:
1. accepted sounds, latest first
2. deferred sounds, latest first

To ease moderation, deferred sounds, with the last message having been written by a user, should be at the top of the deferred sounds:
1. accepted sounds, latest first
2. deferred sounds with the latest ticket sound being by the user, latest first
3. deferred sounds with the latest ticket sound not being by the user, latest first

I used "not being by the user" because tickets are not limited to only the user and moderator posting in it but other moderators may do so as well.

Note, that should this ticket be implemented, it would be helpful for https://github.com/MTG/freesound/issues/534 to be resolved as well.

**Comment by ffont** [comment]
Closing this as invalid as this might have changed since last moderation refactor.
@qubodup if this is still valid feel free to reopen and let us know how it applies to the new moderation interface.
