### ISSUE TITLE
Reposition rating interface to motivate users to rate sound

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#606]
Nobody rates sounds. This is a problem because:
1. Sound artists lose motivation over no feedback even though download count is high http://freesound.org/forum/freesound-project/1080/
2. Lower number of opinions makes trolls be more effective http://freesound.org/forum/freesound-project/33676/

I suspect the reason for this is:
1. the rating interface is too far from the play button in searches and
2. too far from the line between play button and download button on sound pages
3. ratings feel buggy: sometimes you can't rate on sounds (even though they are not yours) without explanation as to why (as of writing this, i can't rate on http://www.freesound.org/people/glitznpearlz/sounds/232213/ ), sometimes you are able to rate your own sounds and your rating is not "remembered" instantly: reloading a page makes it seem as if you have not rated (perhaps because of caching).

I suggest that on sound pages, the stars get moved near the download button or near the play button on sound pages.

For example:
![fsx-1](https://cloud.githubusercontent.com/assets/18312/2642262/3537f160-bf06-11e3-94f0-a31b056e2ed6.png)
I would be glad to create more mockups if anybody has suggestions.

**Comment by ffont** [comment]
We'll try moving the ratings next to the download button as Iwan suggests.
Let's see how these changes the stats on ratings and decide what to do.

**Comment by qubodup** [comment]
Thanks, I look forward to hearing of your results and finding out for myself if I start rating more.

**Comment by ffont** [comment]
After some months we quickly analysed how the rating stats changed. In this picture you can see the number of ratings per day before and after the change in the interface. Before we used to have an average of 220 ratings per day, and after that we have 370, which is approximately 70% more.

![screen shot 2016-06-01 at 12 22 34](https://cloud.githubusercontent.com/assets/478615/15706388/962ce6da-27f3-11e6-88d6-66ac612bdbfe.png)

Thanks for the suggestion @qubodup !

Mentioning also others so you see this message: @bdejong @alastair @andrebola

**Comment by qubodup** [comment]
Nice! Thanks for sharing the analysis!
