### ISSUE TITLE
Some sounds have no type set

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#617]
from bram:
> hey guys,

> have a look at the file type of this sound:
> http://www.freesound.org/people/bone666138/sounds/198855/

> something is severely wrong there...
> might be interesting to check if there are more sounds with weird filetypes.

>  - bram

Looks like it's downloading as valid aiff data:
$ file 198855__bone666138__scratchy-record
198855__bone666138__scratchy-record: IFF data, AIFF audio

If I give it an aiff or wav extension it plays fine. My guess is that we've not saved the type correctly to give it an extension.

Here's the extensions we have in the database. The blank/15 looks like the problem sounds. We should make sure this can't happen.

    type | thecount 
    ------+----------
     wav  |   132411
     mp3  |    18685
     flac |    11520
     aif  |    10729
     aiff |     7821
     ogg  |     1812
     wma  |      104
     m4a  |       51
     amr  |       29
          |       15
     3ga  |        9
     aup  |        6
     avi  |        6
     zip  |        6
     wmv  |        5
     mp4  |        5
     3gp  |        5
     mov  |        5
     mid  |        4
     wave |        3
     jpg  |        3
     prel |        2
     mp2  |        2
     docx |        1
     php  |        1
     mts  |        1
     aac  |        1
     pk   |        1
     swf  |        1
     qcp  |        1
     rar  |        1
    (31 rows)

**Comment by ffont** [comment]
Sounds with wrong extension should be deleted in the server at upload time.

**Comment by ffont** [comment]
I deleted all files with wrong extensions (only those that were not processed/moderated), and fixed the extensions for these files that had empty extension (including rename in disk).
We should not find these problems in the future as we now properly check for valid file extensions at upload time (https://github.com/MTG/freesound/commit/e97dc198bc4ea555d7437905f1de3f4abf0fb9ea)
