### ISSUE TITLE
Sound plays until halfway

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#618]
http://www.freesound.org/people/maccavictoria/sounds/55386/

Waveform and sound are 1m30, but only plays until somewhere around 30 seconds.
Probably needs reprocessing.

**Comment by alastair** [comment]
I downloaded the wav file and it's only 13.5 seconds. It shows as 13.47 seconds in admin too, trying to work out why it displays as 1 minute 30

**Comment by alastair** [comment]
it was because of the cache. I cleared it and now it's showing the correct durations.
