### ISSUE TITLE
id field in solr schema is not sortable

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#631]
Currently the id field in solr schema is not sortable, which means that numeric range filters over sound ids in apiv1 and apiv2 do not work properly. We should either index the field as a sortable integer ('sint' instead of 'integer') or document that numeric range filter can not be applied to sound ids. In any case, it does not make much sense to filter by ranges in ids...

**Comment by andrebola** [comment]
Since this requires a change on solr schema we will do it together with #593
