### ISSUE TITLE
host verification on https

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#637]
we have a process https loadbalancer -> app nginx -> django that rewrites the host between https and appserver (because of our nginx upstream statement).
We thought we were working around this with the x-forwarded-host header and django's settings.USE_X_FORWARDED_HOST=True, but it seems that this still causes problems in django 1.4+'s csrf validation.
Look into what hostname `HttpRequest.get_host()` is using and why the validation is failing.
Also double-check apiv2/`request.is_secure()`

**Comment by ffont** [comment]
Closed because the issue was fixed but ticket not closed.
