### ISSUE TITLE
Player should not seek instantly; Seek should have visual indicator

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#646]
Currently, when clicking a sound image, playback starts at the position of the cursor (seek). This is a usability problem because:
1. There is no visual indicator for the seeking.
2. The default for online media is that clicking the image plays back from the start.
 a. This is of course always default for video (youtube, vimeo).
 b. For sound - a field in which freesound is without competition regarding quality of presentation, when it comes to sound effects rather than music - I have to use Soundcloud (primarily made for music) as an example:
- Soundcloud uses the first click on the waveform to start playback at the start.
- Then, during playback, the mouse cursor can seek, which is indicated by a visual block to the left of the mouse cursor while it hovers the soundwave.
- When paused, seeking is disabled and clicking the waveform continues playback from the current position.

This video illustrates the described behavior: http://youtu.be/PDUKgNXBSYM

If the user wants to play back from the start - which I claim is the case 90% of the time - the user has to move the mouse to the uncomfortably small PLAY icon or try to click the left border, which is both torture, usability-wise.

To my knowledge this instant seek behavior in the Freesound player is a recent addition.

I suggest to revert to old behavior (click while sound does not play back starts playing from start, clicks during playback seek to cursor position) and adding visual indicators to both of these behaviors instead:
1) Before playback, hovering the image should indicate that a click will have the same effect as clicking the PLAY icon. This can be indicated by making the PLAY icon turn red, as it does when you hover it now:
![hover-big](https://cloud.githubusercontent.com/assets/18312/5260124/3c3ea45c-7a0b-11e4-9c99-5d36b5ed70aa.png)
![hover-small](https://cloud.githubusercontent.com/assets/18312/5260130/3ead5cba-7a0b-11e4-94bb-e84ca0e820a8.png)
This might or might not be too subtle.

2) During playback, seek is enabled. Seek is indicated by a yellowish tint over the waveform area to the left of the cursor (not covering buttons):
![seek-big](https://cloud.githubusercontent.com/assets/18312/5260210/0b04537c-7a0c-11e4-8dc3-5849303ad893.png)
![seek-small](https://cloud.githubusercontent.com/assets/18312/5260213/0de00546-7a0c-11e4-988c-76df0badb1fa.png)

Problem to consider: short sounds (1-5 seconds, something Soundcloud is not built for) would effectively not allow seeking or make it very hard. Solutions for this can be:
 a. When the sound is stopped but has been played back before, enable seeking
 b. ignore it, hoping users don't actually use seeking in short sounds or learn to double-click.

**Comment by ffont** [comment]
With the new UI this has been refactored so I'm closing this issue. In the new UI there is visual feedback of the seek position before clicking. This is for devices that have mouse. In touch devices, the playing behaviour is now implemented as described here: first touch starts from beginning, second touch allows seeking.
