### ISSUE TITLE
Memory leak in gearman/workers

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#651]
There is a memory leak somewhere in the processing workers that causes some sounds to fail processing (particularly very long ones) when the machines are running out of memory.
Temporary solution is to restart the workers from time to time, but the leak should be identified and eliminated.

**Comment by ffont** [comment]
As a temporary fix, I set up a cron job to restart processing and analysis workers every hour in processing1 and processing2 (processing1 at *:00 and processing2 at *:30)

**Comment by bdejong** [comment]
Will this kill currently running workers?

**Comment by ffont** [comment]
According to the tests I made, It waits until they finish before restarting.

**Comment by ffont** [comment]
Closing this issue as after new changes in processing we don't observe such behaviour. The cron jobs which restart the workers (and another we added later which cleans /tmp/) have now been stopped.
