### ISSUE TITLE
To many geotags in main geotags map

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#652]
The current way in which we display sounds with geotags in the main geotags map can not handle the number of geotagged sounds that we have in our db (the generated json seems to be too long). We should change the way in which data is acquired so that it can be correctly displayed. Best way is probably to request sounds in pages instead of all at once.

Right now, and to allow the map to load we imposed a limit in the number of sounds that are displayed, but this is only a temporary solution.

**Comment by ffont** [comment]
Actually what happened is that there was a corrupted geotag which broke the javascript al client side (generating an invalid json). Nevertheless, we should improve the way in which the json is requested by the client. Changing from "bug" to "improvement" now.

**Comment by ffont** [comment]
If we want to improve speed we should probably do the clustering on the server.
Have a look at http://postgis.net (postgresql extension)

**Comment by andrebola** [comment]
Right now for the page: https://www.freesound.org/browse/geotags/ took about 1 sec. to load the response and the json was 1 MB.

After doing some research I found that we could use postgis to cluster the markers on the server, the clusters could be generated using [K-means or by a distance ](http://gis.stackexchange.com/a/11778). But we have to do a new request to the server every time the user zoom in the map and calculate the clusters again depending on the position (this could be cached).

The other option is to use solr to return the json information of all the markers, this could be faster of what we have now and easier to implement than the postgis option. 

Solr also supports [clustering of the points](https://wiki.apache.org/solr/SpatialClustering), but I think I would prefer to use postgis in the case of server-side clustering.

**Comment by bdejong** [comment]
There is also: https://cwiki.apache.org/confluence/display/solr/Spatial+Search

Which would enable you do to very quick rectangle searches, but clustering would still be needed at zoomed out viewing.

**Comment by andrebola** [comment]
I think with solr we could reduce only about one second (of querying postgres and generating the json), if that is enough I could do it. Otherwise we would have to implement the clustering.

**Comment by ffont** [comment]
> After doing some research I found that we could use postgis to cluster the markers on the server, the clusters could be generated using K-means or by a distance . But we have to do a new request to the server every time the user zoom in the map and calculate the clusters again depending on the position (this could be cached).

That's right. A simple caching wouldn't help much because rectangle borders are rather "continuous" so it wouldn't be straightforward to define useful cache keys. Maybe we can optimise the json thing by using solr and that's it...
