### ISSUE TITLE
Searching users in admin interface is slow and often returns 500s

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#656]
Reported by Bram,
> sadly enough http://freesound.org/admin/auth/user/?q=forum%40freesound.org 500'ds on me, so I can't check if there is a user with email address forum@freesound.org ...

**Comment by alastair** [comment]
The reason this is so slow is that a search for users in django admin performs a LIKE wildcard query for `*thequery*`, and so it has to search every user, instead of using indexes.
There are a few ways we can improve this:
  - Tell django to not search first name, last name, or email
  - Tell django to search exact matches (so we can use indexes)
  - Install some postgres extensions to allow wildcard searching with an index (I've only had a quick look at this, but it looks like it might be possible)
  - Use something else for search? (no idea how, maybe someone has an extension for the admin backend that lets us use solr for search?)
Mostly for @bdejong, what of these options would work for you? Do you require some certain search tools? Wildcard, search by first name, etc?

**Comment by alastair** [comment]
http://django-haystack.readthedocs.org/en/latest/admin.html cool

**Comment by bdejong** [comment]
- email search is definitely wanted
- first and last name can be removed
- if there is an option to do wildcart searches that would be awesome, but... I'll settle for speed

**Comment by alastair** [comment]
OK, this is about 30-50 times faster now, by removing first name/last name, and adding indexes to email and username so we can do wildcard search.
The extensions we need are not installed on the db server, and in order to add them we need to upgrade postgres (just a small upgrade - from 9.1.13 to 9.1.15). This shouldn't cause us any kind of problem, so I plan to do it early next week.
