### ISSUE TITLE
Add "buttons" for admins and mods.

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#660]
We (admins) and the moderators could use a little automatic button on their profile or in the forum threads. That way their opinion weighs a little more...

**Comment by ffont** [comment]
I'm not sure I understand what that means. Can you elaborate more @bdejong ?
Maybe I've just been reviewing to many old issues...

**Comment by bdejong** [comment]
This was about having a "badge" for forum mods, admins, sound mods so that
when we post something on the forum it says under our names that we are
"special" users.

Still a good idea!

**Comment by bdejong** [comment]
Closing issue in favour of #784
