### ISSUE TITLE
Permanent redirect www.freesound.org to freesound.org

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#664]
In this way we avoid having different domains and cookies problems.

**Comment by alastair** [comment]
www gone!

**Comment by alastair** [comment]
This is causing problems with oauth POST requests to www domain names. We get a redirect, and the http spec says that a client should not re-send post data after a redirect. Some libraries (python) will turn this into a GET, which is invalid.

We need to re-enable www while we choose a solution to not make oauth clients fail. Not sure what the best solution is.

**Comment by alastair** [comment]
So, we just realised that we could do the redirect but have an exception for urls on `/apiv2`. This is done now, and works, and API clients are not redirected.

We should try and contact all API client users to get them to change the access domain to freesound.org without www. However, if there is released software actively being used by users which accesses www, it's likely that we can never add this redirect in place (unless we decide that we want to break the site for x% of users)
