### ISSUE TITLE
Solr 7

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#669]
solr 5 is out. It's new and shiny and doesn't support being run as a .war any more. We could consider building new packages based on this. My maven template is out of date now, I'm not sure what the best way to build with additional dependencies is.

**Comment by alastair** [comment]
solr 6 is out too!
It appears to have geospatial search: https://lucene.apache.org/solr/guide/6_6/spatial-search.html, which might be able to replace our additional dependency.
We should check that the query syntax is the same, as we pass this syntax from the FS API to solr directly. Double-check if anyone actually uses this search, or perform a rewrite of the query syntax before passing to solr.

**Comment by alastair** [comment]
Looks like polygon search still needs JTS: https://lucene.apache.org/solr/guide/6_6/spatial-search.html#SpatialSearch-JTSandPolygons

**Comment by andrebola** [comment]
Last week solr 7 was released, I will try to set up everything for that version.

**Comment by alastair** [comment]
:man_facepalming:

**Comment by ffont** [comment]
Closing this issue as is no longer relevant after all changed we've been doing related to solr
