### ISSUE TITLE
Optimise username lookup in messages

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#676]
The username autocompletion function when composing a message seems to generate slow queries. Should investigate how to optimise this.

**Comment by alastair** [comment]
This should be technically quite similar to https://github.com/MTG/freesound/issues/614

**Comment by andrebola** [comment]
The difference with #614 is that the query filters all the previous contacted users, and also filters by '__starts_with' which is much slower. 

But for my user the query wasn't slow, @ffont can you confirm if this is still an issue?

**Comment by ffont** [comment]
I'm not sure, it might depend on the user.
the filter is starts_with because we want to autocomplete, so I guess we can't do much about it.
maybe we should think of ways to test that, like try response times for different users and see if this is still a problem.

**Comment by bdejong** [comment]
Is this a username completion in the private messages? Because if so
perhaps we should o my look through the users that you wrote to before.

Or, just drop the autocomplete. It's not a great feature.

**Comment by bdejong** [comment]
My apologies. Should have read the description first...

**Comment by ffont** [comment]
This is for private messages yes, it only does autocomplete for users you previously wrote (or wrote you). It is in fact rather useful according to that users said when we implemented it. However, what we could do is replace it by a the same username check in registration, so we do an ajax check that the username exists. At the end I think this is to avoid misspelling usernames. Or maybe we can have both, autocomplete for usernames contacted in the past and username check for others. We could simply compute the list of previously contacted users and send it to the template to do the js autocomplete completely in the client (although this list might get large...).

**Comment by ffont** [comment]
The autocomplete works fine but the username check should not be done for an empty username.
