### ISSUE TITLE
downloading a sound with curl always returns "Invalid token"

### ISSUE THREAD

**Issue by erikparr** [MTG/freesound#681]
I am downloading a sound via curl as instructed here ( https://www.freesound.org/docs/api/resources_apiv2.html#download-sound-oauth2-required ) always results with {"detail": "Invalid token."}
for example (I'm using my working token in place of MY_TOKEN_HERE): 
curl -H "Authorization: Bearer MY_TOKEN_HERE" 'https://www.freesound.org/apiv2/sounds/14854/'
returns 
 {"detail": "Invalid token."}

**Comment by bdejong** [comment]
Hi Erik,

This is a question for http://groups.google.com/group/freesound-api rather than here in github...
Could you please ask on the list?

greetings,

 - Bram
