### ISSUE TITLE
Test if Freesound can now work with aol accounts

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#683]
aol accounts use to give problems in the past with Freesound emails.
For this we introduced some code to not allow users registering with aol accounts. We should test that and see if this is still valid. (see https://github.com/MTG/freesound/commit/0fdfeb40c8bf8563ede587a748555037dd8245e3#commitcomment-12515509)

**Comment by qubodup** [comment]
I created an AOL account and tried signing up on freesound.

The registration form blocks it.

> We are sorry, but aol.com deletes all our emails before they reach you, please use a different provider.

![nope](https://cloud.githubusercontent.com/assets/18312/12806220/400428fa-cb04-11e5-9633-b1d1dd3e2bc8.png)

**Comment by alastair** [comment]
Right - there was originally a problem where our mail provider couldn't reliably send emails to aol addresses, so we blocked it on the registration form.
Now that you have an address, perhaps we can remove the block and see if the registration email arrives to your account.

**Comment by bdejong** [comment]
This was when we were still using the outgoing main at UPF. Perhaps by
using Amazon this is now different.

On Thu, Feb 4, 2016 at 9:11 AM, Alastair Porter <notifications@github.com>
wrote:

> Right - there was originally a problem where our mail provider couldn't
> reliably send emails to aol addresses, so we blocked it on the registration
> form.
> Now that you have an address, perhaps we can remove the block and see if
> the registration email arrives to your account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MTG/freesound/issues/683#issuecomment-179703450>.
>



-- 
http://www.freesound.org
http://www.smartelectronix.com
http://www.musicdsp.org

Mobile: +49 (0) 176 68279940

**Comment by qubodup** [comment]
> Now that you have an address, perhaps we can remove the block and see if the registration email arrives to your account.

Sure, just let me know when I should test.

**Comment by alastair** [comment]
@qubodup can you try and sign up again with your aol address and tell us if it worked?

**Comment by qubodup** [comment]
1. Freesound says:

> Registration done, activate your account:
> 
> We have sent you an email: please check your mailbox (and spam folder if you have one!) for the activation link we have sent you.

2. It arrives in the inbox at aol

3. I can confirm and log in
