### ISSUE TITLE
Using contact form with existing email address does not add user data

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#690]
If a user contacts us who is logged in, user data is automatically added to the email as a footer. This is essential for helping users.

However, lately I seem to be getting emails from not-logged-in-users whose email address *is* in the database, but without a footer.

This needs some careful testing...

**Comment by alastair** [comment]
Fixed in https://github.com/MTG/freesound/commit/4e5fca508a9a2b71ab65de209b73421aea9d6f2f
