### ISSUE TITLE
Log in with email address

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#691]
As a user I would like to log in with my email address so I don't have to remember my username.

As a security measure this should not enable people to check to see if someone has an account on freeosund. I.e. if you just put in an email address and a (wrong) password the error should not say: "your password was incorrect" as this verifies the email address.

**Comment by alastair** [comment]
additionally, the password reset field should allow email addresses as well as usernames

**Comment by alastair** [comment]
4000 users have usernames that look like email addresses (have a @ in them) but the email address is different to the username. I think we should check first the username, and then the email address.
We can adapt our existing auth backend (https://github.com/MTG/freesound/blob/master/accounts/modelbackend.py)

More problematic is that there are 200 email addresses shared between more than 1 user (it looks like no email address is used by more than 2 though, perhaps people forgot their username and created a new account?). We need to either remove them, change the address, or email the users and ask them to make a decision.
Then, we need to make the email address a unique column

**Comment by bdejong** [comment]
That sucks. Can you see if some of those users are inactive? I did not know this, but it looks like django does not enforce email uniqueness:

https://github.com/django/django/blob/master/django/contrib/auth/models.py#L322

**Comment by bdejong** [comment]
btw, you can -for most users- decide on the last_login date if they really need to be contacted: if they last logged in 5 years ago, there is really no need to contact them and we just delete the account.
