### ISSUE TITLE
application logfiles are not being deleted

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#694]
In the `logging.py` config we send a number of log files to `/var/log/freesound` with a `logging.handlers.TimedRotatingFileHandler`. This seems to be configured to only keep 14 old log files, however we seem to have 800mb of log files going back to 2012. Work out why this isn't deleting old log files.

**Comment by ffont** [comment]
We should check if this was fixed.
Adding SysAdmin label.

**Comment by alastair** [comment]
The problem was that the backupCount parameter in logging.py was a string, not an integer as it should be.
Fixed, and log file handler replaced with a ConcurrentRotatingFileHandler so that multiple processes can write to the same file at once (change made in fs-deploy repo + e028983f294e0d8a026ff594815fdd53e9f56cdc)
