### ISSUE TITLE
Getting started / readme in root folder

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#696]
It would be great to have a quick-and-easy way to get into freesound development. This guide shouldn;t cover django essentials (as the django manual is much better for this), but at least a guide to get to an up-and-running freesound would be cool!

A nice vagrant file with some configuration management or bootstrap scripts to get it running locally would be even nicer, but it's understood that this is far from simple.

**Comment by ffont** [comment]
We have the installation instructions in the wiki, but these are kind of outdated and not very well done: https://github.com/MTG/freesound/wiki/Installation-guide

We can make new installation guide, os-agnostic, and with clear separation of what's needed for the core freesound stuff and other things such as search engine. Probably for most potential contributors freesound django app is enough, some other will need search engine too, but few will need processing, etc...

For the the most complicated part of all this is the one of generating data to work with. I think we probably need an automated script to do this, but do it well requires a significant amount of work. Maybe that is something to do through an internship...

**Comment by bdejong** [comment]
I would say that the simplest way for now is to add https://github.com/MTG/freesound/wiki/Installation-guide to the readme :)

And again, any type of "configured for you" configuration with Vagrant would be highly preferred over any other way. Because: then we don't need to have different guides for different OS'es... We just have a vagrant file and some scripts that setup freesound for you...

**Comment by ffont** [comment]
The plan is to move to Docker at some point in the next ~6 months. Once we do that Freesound installation will be much easier.

**Comment by alastair** [comment]
We still need a getting-started document, though. Do you want to use the wiki for this?

**Comment by ffont** [comment]
The wiki is currently so outdated that I honestly don't think if it really helps.
I like getting started guides, but I prefer to wait until we do the docker thing because lots of things will probably be changed.
