### ISSUE TITLE
Add "pending sounds" link for moderators

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#701]
Moderators seem to have trouble finding pending links, which seem to be only reachable from sound items in the sound moderation interface while a user's sound is selected.

Please add a link that is only visible to moderators at two locations:

1. as " (pending sounds)" behind username on each ticket page
![ticket pending link](https://cloud.githubusercontent.com/assets/18312/12697592/2f591d96-c788-11e5-80e9-aed127ae8e4d.png)

2. as " (pending sounds)" behind the number of sounds in a user's profile. 
![user pending link](https://cloud.githubusercontent.com/assets/18312/12697638/2efa4540-c789-11e5-9420-8a916e480bbb.png)

However for number 2, please ensure it is always visible ("Number of sounds: 0" if no sounds uploaded yet. This is regulated by l124-l126 in https://github.com/MTG/freesound/blob/63a03fa4591ccb80d87e98f55b065a344e701cbc/templates/accounts/account.html

**Comment by qubodup** [comment]
Thank you, this is even better with seeing how many sounds are pending!

There are no links in users' profiles though (I guess that's why it was reopened)

Examples:
http://www.freesound.org/people/epimeison/
http://www.freesound.org/people/qubodup

**Comment by ffont** [comment]
I'm not sure I understand, what do you mean the links are not in user profiles?

El 3 febr 2016, a les 13:23, Iwan Gabovitch <notifications@github.com> va escriure:

**Comment by qubodup** [comment]
>the links are not in user profiles

I suggested that links are added to tickets and user profile pages. On http://www.freesound.org/people/qubodup/ this is what I see:
![this](https://cloud.githubusercontent.com/assets/18312/12785584/7d44617a-ca8d-11e5-8504-925abc14279a.png)
no pending sounds link

**Comment by ffont** [comment]
They should definitely be there, only visible to moderators:
![screenshot](https://cloud.githubusercontent.com/assets/478615/12785745/3ea9b090-ca8e-11e5-9c7f-44b5e00aa03d.png)

Maybe it happens that you're not logged in?
I'll double check that permissions are correctly checked just in case.

**Comment by ffont** [comment]
Ups, problem was in the way permissions are checked ;)
Will be fixed in a minute.

**Comment by qubodup** [comment]
Thanks a lot, working now!
