### ISSUE TITLE
don't let a signed in user change their email address on contact forms

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#702]
On the contact form and flag form, we fill in the email address if the user is signed in, but then we let them change it. This can result in some confusion if they do change it - what should we set as the reply-to?
If a user is signed in and uses one of these forms we should not let them change the email.

**Comment by qubodup** [comment]
Some users use temporary, throw-away or secondary email addresses for registration or have shared accounts (school classes). If it's important for us to be able to contact the reporters/writers, it might be good to keep the field.

It also seems simpler to have the same contact form for logged in and nonloggedin users.

If you decide to remove the field for logged in users, it might be good to clarify to them in the form whether they will be contacted by the email in their account or via personal message.

**Comment by ffont** [comment]
Closing this issue as @qubodup seems to have a point and new support system based on Zendesk probably changes a bit all this.
