### ISSUE TITLE
email addresses could be duplicated in users table

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#703]
In some places we look for a user based on an email address (e.g. in the contact form if the user is not logged in), however accounts can have the same email address. We should be careful here that we check this, or implement unique email addresses (#691)

**Comment by qubodup** [comment]
It is extremely common to restrict one user per email address.

Possibly useful info to find the cause of duplicate email addresses: I am able to request the change of a test user's email address to that of my main account using http://www.freesound.org/home/resetemail/ , which should not be possible under a unique-email-address policy.

At the same time, a unique email address policy is already enforced in the registration form:
![reg](https://cloud.githubusercontent.com/assets/18312/12787602/5f740836-ca96-11e5-9b21-a1b31f536921.png)

**Comment by alastair** [comment]
There are a few users who have multiple active accounts with the same email address. We should think about if we want to impose this restriction on them. We'll talk about it further.

Thanks for pointing out the registration form. Perhaps the old accounts were created before this form was added. Maybe that makes it easier to decide if we impose this limit on the other accounts

**Comment by qubodup** [comment]
1. I clarified my previous post in regards to the form which currently still allows me to change a user's email address to one that is already used.
2. Sub-addresses ( https://en.wikipedia.org/wiki/Email_address#Sub-addressing ) might be helpful.
3. Hopefully email requests sent to the users to change their duplicate email addresses with clear overview over their accounts, a brief explanation of why it's necessary (it's a security issue, as part of FS's programming relies on unique email addresses and duplicate email use can't be supported, which means they might cause issues with affected accounts down the line) and how it's done would lead to the users solving the issue.

**Comment by andrebola** [comment]
@ffont can we close this issue now?

**Comment by ffont** [comment]
I'd say yes :)
