### ISSUE TITLE
Remove generic relations on tickets

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#704]
Tickets were initially implemented in a generic way to allow us to have tickets for more objects than sounds, however we have only ever used them with sounds.
This means that the generic relations through the `LinkedContent` object creates much more complexity in ticket handling than it should, especially in sql queries. Newer versions of django make it simpler to do these queries with the ORM, but we should just remove the complexity.

We can just create a `sound` field on `Ticket`. We will have to update all places that deal with tickets.

Additionally, we could add a `date of last comment` and `last commenter` to make tardy user queries much faster (instead of having to do joins and inner queries) to make moderator's lives faster.

**Comment by ffont** [comment]
Most of this changed when we refactored moderation, but I would look at last @alastair's suggestion: 

> Additionally, we could add a date of last comment and last commenter to make tardy user queries much faster (instead of having to do joins and inner queries) to make moderator's lives faster.

This will make moderation pages faster.
