### ISSUE TITLE
Provide short, independent URLs for each sound, use them for credits

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#705]
Sound URLs are long:

http://freesound.org/people/qubodup/sounds/332061/

But YouTube descriptions (for credits) and Tweets are limited in length and long URLs are extremely unappealing when it comes to appearance in credits of video games and film credit rolls.
- Longer URLs have the benefit of informing you of the author.
- Longer URLs (currently) have the drawback of breaking once a user changes their name (this is possibly by manual admin action, happens sometimes when user requests change). I have seen this happen multiple times.

What does it look like on other pages?
- https://soundcloud.com/qubodup/fable
- https://youtube.com/watch?v=Eam0ukCRKKk aka https://youtu.be/Eam0ukCRKKk
- http://qubodup.deviantart.com/art/Free-Pinball-575624409 aka http://fav.me/d9ipmmx
- https://vimeo.com/55279993

I suggest that
1. Freesound provides short URLs for each sound
   This URL should be either
   - http://freesound.org/s/332061 (far from ideal - 10% to be exact (2 out of 22 characters without "http://"))
   - http://freesound.org/332061 (best solution without using custom domain)
   - http://CUSTOMDOMAIN/332061 (best solution but might cause a lot of organizational overhead initially and a little bit of overhead yearly. Domain name suggestion shared on developer mailing list for safety, search for "custom short domain suggestion" to find the right thread).
2. Freesound replaces the URLs used in
   - http://freesound.org/home/attribution/?format=plaintext
   - http://freesound.org/home/attribution/?format=html
   - http://freesound.org/home/attribution/?format=regular
3. Freesound adds a "share" UI element similar to that on deviantart and youtube: a text input field that contains the short url, which auto-selects the text content on first click:
   ![share widget idea](https://cloud.githubusercontent.com/assets/18312/12805740/fb8ba7fc-cafe-11e5-86dc-68ee56fa6878.png)

**Comment by alastair** [comment]
It should be pretty easy to support `/s/songid` or `/songid`. I don't think we need to change to alphanumeric ids.

It's worth pointing out that urls are automatically shortened on twitter, and so don't count towards the tweet length. Perhaps Youtube does the same thing?

We were talking in person, and discussed that it's nice to include the username in urls as another method of citing the sound creator, so I would recommend keeping it if possible. How about 
  * http://freesound.org/user/12343

**Comment by qubodup** [comment]
> it's nice to include the username in urls as another method of citing the sound creator

Agreed.

The current nice system can be preserved but if an (additional) short URL system is implemented, it needs to be short. Usernames are way too long in many cases:

http://freesound.org/people/oceanictrancer/
http://freesound.org/people/omnisounddesign/
http://freesound.org/people/montblanccandies/
http://freesound.org/people/dirtydowntowner/
http://freesound.org/people/paulinamaria1008/
http://freesound.org/people/artesmediales/
http://freesound.org/people/Snapper4298/
http://freesound.org/people/Robinhood76/

Long URLs are a nuisance.

Also, usernames can change and an URL system that omits the username is supportive of that fact. A system that includes the username, can cause confusion in these rare cases.

**Comment by qubodup** [comment]
Update: should this ever be implemented, please do not put usernames in short urls. They can cause huge problems since freesound allows all kinds of characters and again, they can change. See https://github.com/MTG/freesound/issues/759

I also ask that you abandon my suggestions of a custom URL, as I believe getting a new domain and having to manage it in the future is a step that is extremely annoying and stops this problem from being solved. It is also risky, if there is no system in place for ensuring that domain names are paid for and will not run out. So I suggest you just use freesound.org

**Comment by qubodup** [comment]
http://freesound.org/home/attribution/?format=plaintext it is beautiful!

One small suggestion: remove "www." and the final "/" to save 14% of URL length for example in the case of "https://www.freesound.org/s/347576/"

**Comment by ffont** [comment]
Thanks for the suggestion.
Right now because the way in which the url is constructed the www is always added.
This could be changed but it might have unexpected consequences in other parts of the site (because compatibility of www with non-www). I think it would be nice to remove www support at some point (and redirect to non-www), but for now we'll leave it as it is.
