### ISSUE TITLE
Make links work if user changed name

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#706]
If a user changed their name by asking an admin to do so and the admin approved, all links break - to my knowledge.

For example if qubodup used to be called qqqubodup, then after the name change, sound id 331381 would be reachable at
http://freesound.org/people/qubodup/sounds/331381/ but not at
http://freesound.org/people/qqqubodup/sounds/331381/

However all the needed information is available at the old link. The sound ID is unique and the user name is not needed to find the respective sound.

I suggest that Freesound's "page not found" page analyzes the URL and if it has a structure like the following pseudeo-regex:

```
http(s)?://(www.)?freesound.org/people/[^/]*?/sounds/NUMBER(/)?
```

Then it redirects\* to the sound that has NUMBER as an ID - if such a sound exists.

*it should redirect, not provide duplicate content at the wrong URL.

**Comment by alastair** [comment]
One problem with allowing any text to be added as an account name means that people could maliciously put someone else's name in place in the url.
A way around this would be to keep a list of old usernames for each user. As username changes are manual and don't change too often, this shouldn't be too much of a problem with regards to speed or storage.

**Comment by alastair** [comment]
Cool URIs don't change: https://www.w3.org/Provider/Style/URI.html

**Comment by qubodup** [comment]
> One problem with allowing any text to be added as an account name means that people could maliciously put someone else's name in place in the url.

Clarification, just in case:

https://freesound.org/people/qubodup/sounds/177182/ would not deliver the content of https://freesound.org/people/johnhanes/sounds/177182/ while https://freesound.org/people/qubodup/sounds/177182/ is in the navbar.

It would **redirect** to https://freesound.org/people/johnhanes/sounds/177182/ . The URL in the navbar would be https://freesound.org/people/johnhanes/sounds/177182/ .

**Comment by alastair** [comment]
Yes, agreed. This is the way I would do it too. However it would still be possible to use an incorrect citation, e.g. 

 > Uses c8philter4.aif by alastairp, from https://freesound.org/people/alastairp/sounds/177182/

(not everyone looks at the URL when they load a page. I would guess that there will also be people who don't notice that the url of the link and the uploader name is different)

which is what I want to reduce the possibility of. By keeping old usernames for a user we can accept any of their usernames, and none others, which I think is safer.

**Comment by ffont** [comment]
@alastair found some missing things in the implementation of this ticket in https://github.com/MTG/freesound/pull/1059. In general, we need to add a case insensitive index for username in `OldUsername` model, and we need to implement the redirects to all views that use usernames in the URL pattern (not only for sounds app). We should check all the places where the redirect should be added (probably by looking at URL patterns) and then think of the best strategy to handle this (less duplicated code and less DB queries). Also add unit tests.
