### ISSUE TITLE
Show full sound description in moderation interface

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#707]
Often, the full description is needed to moderate a sound. For example to find out whether:
- the recording device is mentioned (to decide whether to approve without comment or with suggestion to include recording device information)
- after the initial non-English language description an English language description follows
- attribution links are included in "remix" uploads
- to see whether software is mentioned for digitally produced sounds/loops

If the information in the shown snippet is not enough, for each affected sound the moderator needs to:
1. click the sound link
2. wait for a page to load
3. change tabs
4. read the description in a new layout
5. close the tab or keep it open to double-check facts in case the moderation message needs to be complex.

To save time, I suggest the full sound description is shown in the moderation interface, both on ticket and moderation queue pages.
# Moderation queue

The moderation queue looks like this in standard and modified ( https://github.com/qubodup/FreesoundSupermod ) UI:

![standard](https://cloud.githubusercontent.com/assets/18312/12871304/1b6c2930-cd74-11e5-8d94-2353dc9d90ff.jpg) ![modified](https://cloud.githubusercontent.com/assets/18312/12871305/1b6c449c-cd74-11e5-8329-56fd762425b3.jpg)

The standard UI has the problem that variable vertical height of the description would move the moderation widget, potentially into unreachable depths. This already happens sometimes when the sound title takes multiple lines of space.

I would like to suggest moving the moderation widget above the sound title/image/description and then allowing the full description to show:

![standard UI suggestion](https://cloud.githubusercontent.com/assets/18312/12871319/6c1c6660-cd74-11e5-98c7-faab448924a3.jpg)
# Ticket page

This is what it looks like right now:

![mod3](https://cloud.githubusercontent.com/assets/18312/12871323/8240ca30-cd74-11e5-831a-4ec3d9761e1b.jpg)

The problem is the same as in the moderation queue. The solution would be the same:

![mod3sug](https://cloud.githubusercontent.com/assets/18312/12871324/91e54ccc-cd74-11e5-835d-794e4092e2d1.jpg)

**Comment by andrebola** [comment]
I think this was implemented in  1928e3f6e8fbda92a17c02354ec4c9294a5c83ca. Now the description is not limited.
