### ISSUE TITLE
absurl templatetag should use https if request is https

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#714]
In https://github.com/MTG/freesound/blob/master/general/templatetags/absurl.py we define the absurl templatetag which acts like url but adds the domain name. This tag only returns urls with http:// and should return https:// when required.

**Comment by alastair** [comment]
This is mostly added to things like emails that we send people. I wonder if we should start just defaulting to https, anyway. So for example, password reset urls are always https, pack detail links are https, etc.

**Comment by bdejong** [comment]
I like your thinking, Alastair. Also, that's an easy fix :)

On Wed, Mar 16, 2016 at 12:09 PM, Alastair Porter <notifications@github.com>
wrote:

> This is mostly added to things like emails that we send people. I wonder
> if we should start just defaulting to https, anyway. So for example,
> password reset urls are always https, pack detail links are https, etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MTG/freesound/issues/714#issuecomment-197264265>
>



-- 
http://www.freesound.org
http://www.smartelectronix.com
http://www.musicdsp.org

Mobile: +49 (0) 176 68279940

**Comment by ffont** [comment]
This was implemented in commit https://github.com/MTG/freesound/commit/6554a3546146a25bbb19bb40e698858e0b7dcffe
