### ISSUE TITLE
describe sounds: on describe page cursor should turn into pointer when hovering over sound in list

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#729]
On the describe page there are instructions " Click on the sound filenames to display the form for describing each sound." but we should make it look more like the filenames are links.

Some ideas to make this more understandable:
- have arrows > which show that it can be expanded
- The cursor should change to a link pointer when we mouse over it.
- use an `<a>` tag so we get underline and text darkening when we hover (need to work out the colours for the "error" case)

**Comment by andrebola** [comment]
I think this is already done, should we close it?
