### ISSUE TITLE
delete links should use POST not GET

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#733]
Some examples:
- user delete (http://localhost:8000/home/delete/, if the user has no sounds)
- unprocessed sound delete (http://localhost:8000/people/alastairp/sounds/274115/delete/)

These pages have a 10 second timeout link, which is good, but it's a destructive operation, and so shouldn't happen in a GET query. If for example a web spider finds this link (probably won't because it's not logged in, but still a possibility), it will automatically follow the link.
Some browser plugins pre-fetch links on a page, which will cause the same thing to happen

**Comment by ffont** [comment]
I guess to close this issue there is still pending to use POST on unprocessed sound delete?

**Comment by andrebola** [comment]
I think for deleting sounds was already changed, see: 
https://github.com/MTG/freesound/blob/14edc52a0c07326ba2816cba291b5525cf132fe5/sounds/views.py#L644
