### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "auth_user_username_upper_key"

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#742]
This seems to be provoked by a form that's submitted two times.
We should probably do the form validation and object save (if validation succeeds) in a single db transaction.

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/274/

```
IntegrityError: duplicate key value violates unique constraint "auth_user_username_upper_key"
DETAIL:  Key (upper(username::text))=(MIKAELPEDERSEN) already exists.

(10 additional frame(s) were not displayed)
...
  File "accounts/views.py", line 119, in registration
    user = form.save()
  File "accounts/forms.py", line 172, in save
    user.save()
```

**Comment by ffont** [comment]
This problems seems to be still happening (https://logserver.mtg.upf.edu/sentry/freesound-web/issues/669/), reopening this issue.

**Comment by andrebola** [comment]
Atomic transaction only assures that if the request is not completed it rollbacks all the changes in the database. I think in this case we need to make sure that the user only executes this part of the code once, for that we could use python locks
