### ISSUE TITLE
Refactor deletion of objects

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#747]
We should improve the way we handle deletion of objects, mainly user accounts and sounds.
Some thoughts:
- When a user wants to delete his account instead of deleting the user object we should anonymise it (change username, email, delete personal data etc...) and mark it as deleted. Then in the templates and views he handle deleted users accordingly (maybe there is in fact nothing to change in how we handle users in relation to that).
- When a user wants to delete her account it should be prompted if she also wants to delete her sounds. If he wants to delete the sounds we delete them (see below), and if he does not want the sounds will continue appearing under the anonymised user (solr index will need to be updated). User Packs should be marked as deleted if sounds are deleted (see below) or should remain unchanged in case user preserves her sounds.
- When we delete a sound we currently create a DeletedSound object that stores basic data and delete all the files. Instead of doing that we should keep the original files and add necessary information do DeletedSound object to be able to retrieve them for research purposes. These sounds will never be shown to the public nor indexed. The urls will still work but only to see that the sound was deleted (in case someone access an old link or something).

Some of these processes might require a large number of queries/actions, maybe we should consider running this asynchronously taking advantage of the gearman server we have already running in processing servers (or find a similar alternative).

Related issues: #735, #733

**Comment by ffont** [comment]
Changes implemented in branch https://github.com/mtg/freesound/tree/deleted-users

**Comment by andrebola** [comment]
@alastair This changes are ready but in order to put this changes in production we need to update the version of postgres to 9.5. When do you think we should do this?

**Comment by alastair** [comment]
I think we can start looking at the upgrade after ismir. I want to set up
the mirror and replication as well. We should plan about a week for the
research, setup, and migration.

**Comment by ffont** [comment]
When users delete their accounts, their forum posts should be also reindexed (as it is done with the sounds). Posts do not have an `is_index_dirty` field so https://github.com/MTG/freesound/issues/753 should be implemented first.

**Comment by ffont** [comment]
To close this issue we still need to do the forum reindex of user posts.

**Comment by andrebola** [comment]
@ffont I think this issue it's related: #753
