### ISSUE TITLE
api query returning pending moderation sound

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound#749]
Doing a query, I got a sound with moderation state pending. Here is what I do :
- query all sounds of Freesound (python client) :
  
  > import freesound
  > client = freesound.Client()
  > client.text_search('') 
- iterate through pager to get further information about sounds :
  
  > ...
  > sound = client.get_sound(345682)
  > FreesoundException: code=404, detail="{u'detail': u'Not found.'}"

In the web, I could find the sound using a query by id :
http://freesound.org/search/?q=345682&f=&s=score+desc&advanced=0&g=1

When trying to access to the sound, page is not found...

This sound may not be return by any query I guess.

**Comment by alastair** [comment]
This sound is in moderation, but has processing state OK. Perhaps it was added and then unmoderated.

However, I checked a few things:
index dirty was false. I set it to true and ran post_dirty_sounds_to_solr, but it stayed dirty??

I ran the queries in the management command, and saw that there are 1986 dirty sounds to remove (index_dirty=true, but processing or moderation is not ok). Many of these are not in solr. Perhaps we should set the flag outside the solr check? https://github.com/MTG/freesound/blob/master/search/management/commands/post_dirty_sounds_to_solr.py#L51

this sound appears in the sounds_dirty_to_remove list, but running the management command doesn't delete it.

I manually searched for the sound and ran the solr delete option, and it got deleted from solr

**Comment by ffont** [comment]
It looks like as alastair says the sound was added to solr and thenw as unmoderated for some reason but the deleting from solr did not work.
It will probably be hard to investigate why, but maybe as alastair says the delete from solr form the command does not work. We'll have to investigate.

FYI: We have a command "report_index_statuses" which compares all indexes and changes sound index states accordingly. This is not triggered by a cron, but it is useful to have an idea of the synchronisation status of the indexes.

**Comment by ffont** [comment]
Closing this issue as this was probably an isolated case. Solr index does not seem to have been out of sync since then. If it happens again we'll look at it.

**Comment by ffont** [comment]
Closing this issue as this seems to be an isolated case.
Solr index seems to have been on sync since then. If it happens again we'll investigate more.
