### ISSUE TITLE
Revise pack download functionality

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#751]
When packs are downloaded a zip file is created on the fly which includes sounds plus a license file (with a list of sounds and their licenses). If I recall correctly, on osx that zip file needs to include some checksum so that it can be opened correctly. For this reason we have to create the license files beforehand every time a pack is edited, which creates a number of other problems.
We should investigate if we can create these files on the fly and avoid having them precomputed. Eventually this will render Pack.process() method useless and we'll be able to get rid of this (which will simplify many bits of fs code).

**Comment by andrebola** [comment]
After we talked I changed the code to generate a temp file with the license information. I decided to use python's tempfile module to handle the names of the temp files so there is no collision. Then, my idea is to use a cron to remove the files older than one week. Like this: 
```
find /path/to/files* -mtime +7 -exec rm {} \; 
```

Also, as @ffont suggested I made the method generic so it can work with any set of sounds, but I'm not sure about the text in the license file  :
https://github.com/MTG/freesound/blob/temp-license-file/templates/sounds/pack_attribution.txt

**Comment by andrebola** [comment]
Following the suggestion of @alastair I re-implemented this issue. Now it doesn't need to use the filesystem since nginx queries a url to get the license file content.

**Comment by ffont** [comment]
@andrebola can this be turned into a pull request?

**Comment by ffont** [comment]
Closing this issue as all was implemented and deployed :)
