### ISSUE TITLE
Async user delete option

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#754]
We should implement the option of deleting users in an async manner, so that admins can schedule deletion of a user.
This could be implemented similarly to the whitelist_user option, using a gearman async task. It should support three methods for deleting users (full db delete, delete including sounds, delete keep sounds).

**Comment by ffont** [comment]
We could also add a fourth option which is to delete only the sounds of a user.
Might become handy in some situations.

**Comment by andrebola** [comment]
I think it would be better to have this fourth option in a separe method since is not related with deleting the user. 
This method should be very clear on what is doing since is not possible to undo the changes.

**Comment by ffont** [comment]
I see that we're using more and more async actions and in the way we're doing it we need to run a different gearman queue for each one. Maybe we should simply have one queue for the async actions like whitelist and delete and then indicate the particular thing to do using the "action" parameter. This also applies to the notify random sound.

Therefore instead of merging this branch I'd refactor the whole async tasks thing (well, processing and analysis we can keep them as they are, with a separate queue). Shouldn't be too much. Also this will mean that we don't need to change deploy config every time that we add new async tasks.

**Comment by andrebola** [comment]
I think I can change the worker to use a single queue, without having to change the code that calls the worker. Otherwise we would have to change the code several parts.

**Comment by ffont** [comment]
We have implemented the delete functions and the infrastructure to do the delete asynchronously. We still need to add the links in the admin page. However, it would be good to add some functionality that shows what is going to be deleted in a delete page confirmation (just like in normal delete from django admin). Maybe the same thing can be reused? we should investigate.

**Comment by andrebola** [comment]
This changes are read on #788

**Comment by ffont** [comment]
Closing this issue as this was already implemented and deployed
