### ISSUE TITLE
Offer user possibility to change password

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#756]
Currently we -strangely enough- only offer users to _reset_ their password in their settings ( http://freesound.org/home/edit/ ). This is weird, because if you are logged in, why would you want to _reset_ your password?

I sometimes need to send people a new password (after changing it for them in the admin) and then I would like to be able to say: "now go <here> to change it again" - but I can't.

It looks like implementing this should be relatively easy as Django already implements the right form and everything:

https://docs.djangoproject.com/en/1.10/topics/auth/default/#all-authentication-views

see "password_change"

**Comment by ffont** [comment]
Also the password reset we have we implemented manually (probably back in Django > 1.4 this there was no built-in password reset view). Maybe we could refactor it using django built-ins.

**Comment by andrebola** [comment]
The urls for change-password were already working, I just changed the templates and the link in user settings.
