### ISSUE TITLE
Provide short, official, ASCII-only user and sound URLs for easier attribution

### ISSUE THREAD

**Issue by qubodup** [MTG/freesound#759]
Freesound allows all kinds of characters in usernames. This can become a problem when trying to provide attribution in a restrictive or buggy system to create a credits screen for a video or in a video game engine, or a video host website or restrictive (no special characters, no unicode, max character count) content generators (website, video...).

It always becomes a huge problem when a lot of sounds are used.

Please reserve the following URL spaces:

freesound.org/s/[sound_id]
freesound.org/u/[user_id]

Visiting these pages will **redirect** to the full URL of the sound or user page. This is how every website with official short URLs does it. Example: https://youtu.be/A9CZLSaJhl4

YouTube messed with its user URL system so often, it is a mess. Each of the following URLs provides the same content without redirecting to a "true" URL.
https://www.youtube.com/qubodup
https://www.youtube.com/c/qubodup
https://www.youtube.com/user/qubodup
https://www.youtube.com/channel/UCGy7ppDyzQ4JX9WsSfkN6ow

What I suggest for freesound is clean: there is one short url and it redirects to the full one, just like the sounds or youtube video pages.

sound ID can be the current sound ID or a hash of it to make it even more compact.
user ID can be the internal user ID or a hash of it to make it even more compact. They can _not_ be a hash of the username, since username changes are common https://github.com/MTG/freesound/issues/706

I recommend against hashes, because they might cause additional headaches to make them language-safe: http://programmers.stackexchange.com/questions/143405/how-to-generate-language-safe-uuids

Making it easier to link to users and their sounds will benefit all.

**Comment by ffont** [comment]
I think what you propose makes sense.
Let's if the others have something to say.

**Comment by ffont** [comment]
Related issue (if not duplicated): https://github.com/MTG/freesound/issues/705

**Comment by ffont** [comment]
Done and deployed in https://github.com/MTG/freesound/pull/766
