### ISSUE TITLE
Switch to open street maps?

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#760]
It would probably be good to switch to an open alternative for maps.
Google announced updates in the [google maps api standard plans](https://googlegeodevelopers.blogspot.com.es/2016/06/building-for-scale-updates-to-google.html?utm_source=email&utm_medium=social&utm_campaign=2016-geo-na-website-gmedia-blogs-us-blogPost&utm_content=TBC). This will probably affect our usage of the API.
Maybe we should take this opportunity to move to open street maps instead.

We should first evaluate which implications would this have. We use google maps for a number of features and there are things that should be taken into account. Here is a probably incomplete list of things to consider:

- Map in user profile page
- Map in pack page
- Map in browse geotags page (including versions filtered by tags)
- Map sharing options in browse geotags page
- Clustering of sounds in map (currently done client-side)

**Comment by andrebola** [comment]
I changed the code in  https://github.com/MTG/freesound/blob/master/templates/accounts/account.html to use [openlayers 3](https://openlayers.org/) and open street maps, it looks like this:

<img width="373" alt="captura de pantalla 2016-10-19 a las 1 55 20 p m" src="https://cloud.githubusercontent.com/assets/991305/19528824/e6bb87f4-9603-11e6-83ac-2ea66c7c172a.png">

<img width="359" alt="captura de pantalla 2016-10-19 a las 2 04 04 p m" src="https://cloud.githubusercontent.com/assets/991305/19529097/ef3ee104-9604-11e6-8abf-13fbbe8dc12e.png">

Before changing the others I would like to know your opinion about this. 
I couldn't find a (free) option for using satellite images, I don't know if this is an issue for you.

**Comment by bdejong** [comment]
Hmmm... there are a lot of sounds which are in rural areas that don't have roads, ... how will people figure out where to put their markers?

**Comment by ffont** [comment]
Hmmm, I think we definitely need satellite imagery...
For what I see open street map does not support that, only vector data.
I also searched a bit and there do not seem to be open alternatives.

**Comment by ffont** [comment]
Closing as invalid as we checked and we are way below the requests limit for google maps so we can continue using their satellite imagery.
