### ISSUE TITLE
Activation email not sent when "+" in address

### ISSUE THREAD

**Issue by noah-sis** [MTG/freesound#765]
I tried to register for an account today and used a "+" in my email address (example: `JDoe+freesound@example.com`) but never receieved a confirmation. When I attempted to register again without the postfix (`JDoe@example.com`), the email went through and everything was just fine.

It appears that somewhere along the chain, something is getting confused by the "+" in the address (a *valid*, but somewhat uncommon, character) and is failing silently (to the user, at least).

This is a minor bug, but nonetheless an inconvenience for those of us that like to keep our inboxes organized through this method.

Incidentally, there is an unregistered ghost account of mine now floating around. I'd be happy to privately provide details of it so that it may be removed should the devs ask.

Thank you!

**Comment by alastair** [comment]
Thanks for the report. We're familiar with the `+` suffix in email addresses, and in fact we thought that we had tested this. I'll double-check our setup to make sure that it's working as expected.

If you want your unregistered account deleted, you can email us at support@freesound.org, or wait until we automatically delete old inactive accounts.

**Comment by noah-sis** [comment]
Thanks for the quick response, @alastair. I appreciate that you all specifically tested this; far too many sites fail to. Too bad stuff just quits working sometimes, huh?

Thanks again!

**Comment by noah-sis** [comment]
Found at some point later that this was actually due to something with our organization's web server, but I forgot about this issue. My apologies for not closing this earlier!
