### ISSUE TITLE
Donations thanking

### ISSUE THREAD

**Issue by andrebola** [MTG/freesound#771]
After discussing it with Xavier, I want to open this discution to know if there is a better way of thanking the donations we receive.

I guess pledgie sends an email to the donators but It would be good to thank them in a more personal way, it would be better if we could contact them or at least show their names somewhere. The same happens with the t-shirts.

I couldn't find a way to get a callback from pledgie when someone donates, but there is an API to query the donations: https://pledgie.com/accounts/freesound.json?_method=get

**Comment by bdejong** [comment]
TBH if we want to spend time on the donations it would actually be better to make something that integrates directly with Paypal: Pledgie takes an additional cut on top of what paypal takes and this is a bit... silly.

https://pledgie.com/site/faq - "Pledgie keeps 3.0% from every donation to help support pledgie.com"

**Comment by andrebola** [comment]
I think Paypal also charges for donations (2.9% + 0.3c), but there is a discount for registered non-profit. 
https://www.paypal.com/us/webapps/mpp/donations

**Comment by alastair** [comment]
That's only for US organised registered as non-profit with the IRS, which won't work for us.

We should only show users if the want to be public, by giving them the option make their donation public with a checkbox, etc.  Perhaps we could send a personal email to users who don't want to be public, and display the others :)

**Comment by ffont** [comment]
I think that's a good Idea, having a list of donors (that want to appear publicly) is nice.

**Comment by bdejong** [comment]
@andrebola yes, paypal taks an ADDITIONAL 3%. So, we lose 3% and then another 3%. Which is exactly what I'm saying...

If we would use the paypal API directly we'd only use 3% one time.

**Comment by andrebola** [comment]
@bdejong thanks, I realized that later. 

I will starting working on this, I will put a simple donation button and a list of donators.

**Comment by ffont** [comment]
Closing this issue as was implemented in https://github.com/MTG/freesound/pull/774 and already deployed
