### ISSUE TITLE
oEmbed functionality

### ISSUE THREAD

**Issue by waterjump** [MTG/freesound#773]
Currently id-to-embed code functionality requires manual construction.  oEmbed is a standard for getting embed codes without the need for private API access or special parsing.

**Comment by bdejong** [comment]
On every sound page there is the embed code which you can easily copy-paste. I don't know how implementing a relatively old standard from 2008 (which was never really widely adopted by oEmbed consumers) would make things better.

Could you give us some better insights, @waterjump ?

**Comment by waterjump** [comment]
oEmbed is used to get the embed code programmatically using the direct link to the sound, rather than a human user navigating to it, copying the existing embed code.  I only suggested this because I'm tasked with embedding audio samples from Freesound, in addition to SoundCloud and YouTube, and I have to manually parse out the sound number.  Here's what it looks like in Ruby:

```ruby
if audio_sample.include?('freesound')
  freesound_id = /\d{6}/.match(audio_sample).to_s
  return unless freesound_id.present?
  "<iframe frameborder='0' scrolling='no' src='http://www.freesound.org/embed/sound/iframe/#{freesound_id}/simple/small/' width='375' height='30'></iframe>"
end``` 

oEmbed will also prevent code like this from breaking if sound ids change format, for example from 6 digits to 7.

**Comment by bdejong** [comment]
Sean, sounds already have from 2 to 7 digits: https://freesound.org/people/Bram/sounds/11/ is the first sound in the database

**Comment by ffont** [comment]
Implemented in https://github.com/MTG/freesound/issues/853
