### ISSUE TITLE
Add 'delete post' option on forum moderation

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#789]
Currently when moderation forum posts there is only the option of approving a post or deleting the user (and the post). This works most of the time because posts which are not approved are mostly spam. But sometimes there might be some inappropriate posts that should not be approve but there is no need to delete the user. In that case it would be good to have a 3rd option to remove the post/thread only.

**Comment by bdejong** [comment]
Do we have concrete examples of this? Otherwise I would say this is not
really needed...

**Comment by ffont** [comment]
Hmm I remember finding myself in that situation sometimes and wishing I had this, that's why I finally opened the issue. Now I couldn't put a specific example but I will if it happens again.
