### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 21: invalid continuation byte

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#793]
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/313/

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 21: invalid continuation byte
(17 additional frame(s) were not displayed)
...
  File "rest_framework/request.py", line 193, in user
    self._authenticate()
  File "rest_framework/request.py", line 316, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "apiv2/authentication.py", line 48, in authenticate
    super_response = super(OAuth2Authentication, self).authenticate(request)
  File "oauth2_provider/ext/rest_framework/authentication.py", line 18, in authenticate
    valid, r = oauthlib_core.verify_request(request, scopes=[])
  File "oauth2_provider/oauth2_backends.py", line 167, in verify_request
    valid, r = self.server.verify_request(uri, http_method, body, headers, scopes=scopes)
```

**Comment by ffont** [comment]
Apparently you can reproduce the problem sending a query like this:
```
http://xxxx/apiv2/search/text/?query=ambient&filter=tag:(rain%20OR%CAfe)
```
I'm not sure if this covers "all of it". We should probably raise an issue in the rest framework repo and see what they think. Still we should first make sure that we're not doing any processing to this data which might be causing this. I don't think so but I remember we overwritten some methods in rest framework classes.

**Comment by alastair** [comment]
For data that we control (e.g. query parameters like @ffont's example) we should validate it before we use it. However, I think this error is caused by rest framework + oauthlib trying to verify the data before we get access to it in the view. So we need to work out if this is a bug in oauthlib that should be reported upstream, or if we need to wrap our entire auth function in a try/catch for unicode errors.

Also: See what happens on python3

**Comment by andrebola** [comment]
See: https://github.com/evonove/django-oauth-toolkit/issues/202

It looks like we should update oauthlib to 2.0

**Comment by andrebola** [comment]
After updating django-rest-framework to 3.6 and oauthlib to 2.0 the error still occurs, so I think the related [issue](https://github.com/evonove/django-oauth-toolkit/issues/202) says it has been fixed for oauthlib 2.0 using python 3.

**Comment by alastair** [comment]
It looks like this is happening with some other parameters too - 

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/974/

**Comment by philtgun** [comment]
Details of [sentry event](https://logserver.mtg.upf.edu/sentry/freesound-web/issues/974/):
```
ValueError: Invalid hex encoding in query string.
...
  File "apiv2/authentication.py", line 49, in authenticate
    super_response = super(OAuth2Authentication, self).authenticate(request)
  File "oauth2_provider/ext/rest_framework/authentication.py", line 18, in authenticate
    valid, r = oauthlib_core.verify_request(request, scopes=[])
  File "oauth2_provider/oauth2_backends.py", line 167, in verify_request
    valid, r = self.server.verify_request(uri, http_method, body, headers, scopes=scopes)
  File "oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "oauthlib/oauth2/rfc6749/endpoints/resource.py", line 68, in verify_request
    request = Request(uri, http_method, body, headers)
  File "oauthlib/common.py", line 404, in __init__
    self._params.update(dict(urldecode(self.uri_query)))
  File "oauthlib/common.py", line 138, in urldecode
    raise ValueError('Invalid hex encoding in query string.')
```

Need to check how different is new `ValueError` to previous `UnicodeDecodeError` and if the scenario is the same.
