### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 5: ordinal not in ...

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#807]
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/555/

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 5: ordinal not in range(128)
(12 additional frame(s) were not displayed)
...
  File "accounts/views.py", line 273, in edit
    if profile_form.is_valid():
  File "utils/forms.py", line 41, in clean
    return clean_html(value)
  File "utils/text.py", line 183, in clean_html
    soup = BeautifulSoup(input, fromEncoding="utf-8")
```

**Comment by andrebola** [comment]
I tried to set some non ascii characters on my local and it seems to work fine, I also think if we were breaking the input because of some wrong encoding then we would see this error most often (this is the only occurrence of this issue). Also note that the email address of the users is suspicious.
