### ISSUE TITLE
Add more statistics to monitor/stats page

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#808]
We recently introduced a nice statistics page for Freesound only accessible by admins. @andrebola added some stats that he considered interesting, but we could add other interesting stats. The goal of this issue is to brainstorm a bit about which stats could be added and then add them ;)

The following are new stats to add which are "single numbers", so these could be shown in a table at the top of the stats page, no need for evolution plots (although the computation of these should also be cached):

- N registered users `User.objects.filter(is_active=True).count()`
- N uploaders `User.objects.filter(is_active=True, profile__num_sounds__gt=0).count()`
- N sounds (moderated+processed ) `Sound.objects.filter(processing_state="OK", moderation_state="OK").count()`
- N packs `Pack.objects.all().count()`
- % of sounds inside a pack (total sounds with pack non null/total sounds)
- N downloads `Download.objects.all().count()` + avg n downloads per sound
- N comments `Comment.objects.all().count()` + avg n comments per sound
- N ratings `Rating.objects.all().count()` + avg n ratings per sound
- N tags `Tag.objects.all().count()`
- N tag applications `TaggedItem.objects.all().count()` + avg tag applications per sound
- N posts in forums `Post.objects.all().count()`
- N threads in forums `Thread.objects.all().count()`

Also we could add new "graph" stats for "number of donations in the last week" and maybe including amount donated?

Also I think that maybe we can set a cronjob that retrieves the monitor/stats page once a day early in the morning, so the numbers are already computed the first time an admin loads it ;)

**Comment by andrebola** [comment]
The graph that currently shows number of Downloads could be improved since the number of sounds is much bigger than the number of packs so it's imposible to see a variation in the packs, it would be better to either show the packs in a different graph or instead of showing the number of packs we could graph the number of sounds downloaded in the form of packs (sum the number of sounds on each downloaded pack).

The tags graphs is not very clear, currently shows the 30 most used tags on new sounds of the last week, I think it would be better to show a line for each tag showing the position for each day, something like this:
![f15e22b4-3b7f-11e5-9496-12b6d811f0ea](https://cloud.githubusercontent.com/assets/991305/23403762/5a4ff1a2-fd90-11e6-8fad-d547de6659ed.jpg)

It would be interesting to display also the most used tags of the downloaded sounds in the last week.

We could display the tags more present on the entire system (not just one week) and it could be interesting to compare this tags with the most common query terms so we can check if the interests of the users are met, otherwise we could encourage the users to upload some king of sounds, or maybe they are just missing the important tags?.

This information could also be sent by email monthly, like a resume of the activity. We could even send personalized mails depending on what the user searched.

**Comment by ffont** [comment]
>  graph the number of sounds downloaded in the form of packs (sum the number of sounds on each downloaded pack)

great idea!

> It would be interesting to display also the most used tags of the downloaded sounds in the last week.

Also a good idea so we see what people is downloading. Honestly to me it's still not clear if this is the best graph to use, but lets give it a try. Also I would extend last week to last 2 weeks (this applies to all graphs, I think I already commented this in the PR)

> We could display the tags more present on the entire system (not just one week) 

Well this is basically the main tagcloud

>  the most common query terms so we can check if the interests of the users are met

Query terms we can get them from graylog for a particular time period (~months). Maybe we can do it also from the downloaded sounds so we can do this "all time". We could have the "all-time uploaded sound tags  tagcloud", and the "all-time downloaded sounds tagcloud"

> This information could also be sent by email monthly, like a resume of the activity. We could even send personalized mails depending on what the user searched.

After we "perfect" the stats page we could think of making a public version of it, and the even sending by email or something, I agree. Although we should make sure that we only send it to people who's interested.

**Comment by bdejong** [comment]
> The graph that currently shows number of Downloads could be improved since the number of
> sounds is much bigger than the number of packs

Why not simply use two axis on the plot? One on the left one on the right?

![weight_loss](https://cloud.githubusercontent.com/assets/805269/23405489/c06a3ef0-fdba-11e6-90d6-0d4a85c246d1.jpg)

**Comment by ffont** [comment]
> > The graph that currently shows number of Downloads could be improved since the number of
sounds is much bigger than the number of packs

> Why not simply use two axis on the plot? One on the left one on the right?

Still I think that number of sounds download "via" packs is an interesting number, so maybe have all of them :)

**Comment by ffont** [comment]
Also regarding donations we could add things like:

- Total donated amount since 1st jan
- Total number of periodic donations (if we have this information, I think we can store it when paypal notifies us of a donation)

**Comment by ffont** [comment]
Things missing to implement:
- Change Packs graph for number of sounds in pack
- try other graphs to display tags, use cloud of tags to display the most used tags
- display most used tags on downloaded sounds (we currently show the most common tags on uploaded sounds)
- See how to get most frequent query terms from graylog
- Add totals of donations

**Comment by bdejong** [comment]
I'd really love to see the "actual active users" per month or week... Defined as: an active user is someone who has commented/uploaded/downloaded/..... something in freesound during that month/week.

Returning users would also be awesome, as in "this user was active last month as well" but this might not be as easy...

Currently we have "activated users" which doesn't mean as much as we have a LOT of people who just logged in, downloaded one sound and left again...

**Comment by ffont** [comment]
Hi,
I just merged and deployed a new bunch of small updates as in PR https://github.com/MTG/freesound/pull/811.

I completely agree with what Bram suggests, therefore let me update the list of "pending" stats to implement:
- [ ] try other graphs to display tags, use cloud of tags to display the most used tags (tagcloud of uploaded sounds)
- [ ] display most used tags on downloaded sounds (tagcloud of downloaded sounds). Both this and the previous one could maybe be computed for "last two weeks" and "all time".
- [ ] Amount of donations per week (graph os we can see evolution).
- [ ] Active users per week. Number distinct users that either downloaded, uploaded, commented, rated or posted in forums. Also here we'd have a graph so we see evolution.

**Comment by andrebola** [comment]
It there anything else to do about this issue?

**Comment by ffont** [comment]
I think for now we can close, and if we want to add/update more things in the future we create a new issue.
