### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/home/fsweb/freesound/freesound-data/uploads/5937039/Simple...

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#816]
This may have been related to our swapping of storage locations. In any case, we should probably wrap this in a try/catch.

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/290/

```
OSError: [Errno 2] No such file or directory: '/home/fsweb/freesound/freesound-data/uploads/5937039/Simple Gunshot.wav'
  File "accounts/views.py", line 500, in describe_sounds
    os.remove(forms[i]['sound'].full_path)

OSError: [Errno 2] No such file or directory: '/home/fsweb/freesound/freesound-data/uploads/5937039/Simple Gunshot.wav'
```

**Comment by ffont** [comment]
Make sure in our Sentry logs that this error always occurs at `os.remove(...)`. If that is the case, for this issue we simply need to handle the exception and pass (or log).

**Comment by alastair** [comment]
Also happening in another part of freesound

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/685/

This code is the same, we should break it out into a helper and call it from both places (and also check if we remove a sound like this in other places).

**Comment by alastair** [comment]
@ffont pointed out that the second error might be related to double-click on the describe page. We should check if this seems to be the case.
If we want to start disabling buttons to fix double-click then we should open a ticket for it and make some documentation to explain how we can easily apply this to many pages without duplicating code.

**Comment by alastair** [comment]
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/705/
