### ISSUE TITLE
Frame load interrupted error when downloading in safari

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#836]
When clicking on the download button in sound page safari shows an error in the console "Failed to load resource: Frame load interrupted". The sound downloads without problems, but the error stops the execution of the `onclick` events of the button. This means that the download event is nor properly registered in google analytics and that other js code we run (recently we added the [after download modals](https://github.com/MTG/freesound/pull/820) stuff) does not get executed.
This problem only happens in safari and has been [reported by other people](https://www.google.com/search?client=safari&rls=en&q=Failed+to+load+resource:+Frame+load+interrupted&ie=UTF-8&oe=UTF-8) to be happening. 

After a couple of hours doing some research about that I could not find an optimal solution, and only a workaround which I implemented in this commit: https://github.com/MTG/freesound/commit/abfac7d9e066924b3ac07367ac710ff9daef2d22. The workaround is only applied if the browser is Safari (using basic user agent comparisons) and does two things: 1) set download's link href attribute to `javascript:void(0);`, and 2) bind a `click` event which waits 100ms and sets `window.location` to the download url (triggering the download).

This issue should be reviewed and a better solution found...

UPDATE:
The workaround has been further improved in https://github.com/MTG/freesound/commit/569ffa0e8db2b3f01a1e381d8b2dc5906976dcf2 thanks to @alastair suggestions. Instead of triggering the sound download inside a `setTimeout`, we trigger 'after download modal' and 'google analytics' calls inside the `setTimeout` and leave the original `href` link behaviour of the download button. This also allows the 'after download modal' and 'google analytics' to run and doesn't break downloads when javascript is not turned on.

**Comment by davidpelayo** [comment]
[Related to this discussion](https://github.com/eligrey/FileSaver.js/issues/215#issuecomment-302668297).

Now on latest Safari release, this gets fixed. See [more info here](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html).

**Comment by ffont** [comment]
Closing this issue as it requires no action from our side.
The bug will still be present for users without the latest version of Safari, therefore the workaround for the after download modal still needs to be there.

**Comment by ffont** [comment]
We should revisit and reevaluate this issue as recently I've been experiencing it happening again on safari
