### ISSUE TITLE
email stream settings explanation & confirmation

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#837]
![screen shot 2017-04-04 at 17 31 06](https://cloud.githubusercontent.com/assets/805269/24665073/9321907a-195c-11e7-8450-8d5d29ded27e.png)

1. The last setting should be: get a weekly update on all users and tags you follow.
2. when you save there is no indication that something actually saved.

**Comment by andrebola** [comment]
1 -> Done

**Comment by ffont** [comment]
@andrebola does your comment mean that you're working on it? ;)

**Comment by andrebola** [comment]
No, I just changed that text on the admin.  
(sorry about the short comment) But I can do the second part if you want

**Comment by ffont** [comment]
but is it committed somewhere?
