### ISSUE TITLE
Choose sound of the day and send emails using a cron job

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#839]
Currently we choose the sound of the day on page load if the item does not exist in the cache. This means that for one unlucky person per day (or more, if we clear the cache), page load takes an additional 500ms (#593) and then an email send is triggered (to tell the user that their sound was chosen)

It's perhaps not a good idea to do this kind of processing on page load, and we should think about moving it to an external cron job so that 1) external users are not affected, and 2) we don't have a random view sending unrelated emails - we can conceptually group these together in a single command (https://github.com/MTG/freesound/commit/3ed41a746c475997a4a302175d2a60ead7bc6d06#commitcomment-21546471)

Some possible issues:

* If we don't perform a check on page load, there may be no sound of the day
* If we perform the cron job too infrequently then there might be a gap between the sound expiring from the cache and choosing a new one
* If the cache is cleared then there will be no sound

Some solutions
* Make the script choose tomorrow's sound instead, so we always have an extra one waiting
* Think about using Redis instead of memcache - redis can serialise to disk, and can also have separate namespaces. We could have a volatile namespace for things like page caches and a more permanent one for sound of the day
* Think about putting sound of the day history in the database - this lets us be smarter about not choosing the same sound twice, or sounds by the same author too often (so that they don't receive too many emails!)

**Comment by bdejong** [comment]
This actually happens to multiple pages. /Sounds/ probably too...

On top of that I think you can have multiple regenerations at the same
time. I.e. cache miss -> 500ms -> multiple more misses.

It might be interesting to cron this in a generalized way... I.e. have one
cron which can generate multiple memcached-stored HTML fragments...

**Comment by alastair** [comment]
In the case of the sound of the day only an sound ID is stored in memcache, we're not storing any rendered data. 

I only bought up the page caches because everything is stored in memcache in a single namespace. I was suggesting that we think about separating items which are completely stateless (such as the cache of a template, we can just recompute it at any stage), and things that require a bit more state (such as the sound of the day ID, which should theoretically stay the same for a 24h period...)

**Comment by bdejong** [comment]
Aha, okay...

Btw the tricky part might be the cache warming... If we have parts of the
website which are only generated via a cron, what do we do when we start
from a cold cache? Not display those parts? Does that make sense for
everything?

**Comment by ffont** [comment]
I don't know it it makes sense, but we could combine both strategies in a way that we try to load X from cache, if X is not in cache we compute in on page load (like it is now), but we also run cronjob to compute X so we greatly reduce chances that X is not in cache. Not sure if it makes sense.

**Comment by bdejong** [comment]
Not a bad idea! But then making 100% sure that this happens "once every 24 hours" is starting to sound like rocket science :-)

**Comment by ffont** [comment]
btw, going back to the core of the issue @alastair's idea of storing random sound in db is great. It will allow us not do things like not repeat sounds/users in X days bla bla bla. On page load we always read last chosen sound of the day, and then we have a daily cronjob that adds a new random sound of the day.

Deal?

**Comment by alastair** [comment]
It looks like emails aren't being sent. I'll open another PR
