### ISSUE TITLE
Unify timestamp formats in API responses

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#846]
See message thread in API mailing list: https://groups.google.com/forum/#!topic/freesound-api/IZaorD_kBfI

When returning timestamps (like sound creation date) we do it with different time resolutions depending on the record. Best guess is that records created before the switch to postgres in 2011 use millisecond resolution, while records created with postgres use microsecond. We should unify the format of timestamps, probably best way to do it is in the object serializers (https://github.com/MTG/freesound/blob/master/apiv2/serializers.py).

**Comment by alastair** [comment]
We can do this by doing `thedate.replace(microsecond=0)` before rendering it. There's probably no reason to have more resolution than second in creation dates.

**Comment by ffont** [comment]
Also we should take care of that resolution problem when indexing to solr. Maybe it's not a problem at all, but we should make sure that sound timestamps are indexed with a unified format.
