### ISSUE TITLE
Split requirements files & pin versions

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#849]
Currently all requirements are on one big file, but only a selection of them are needed for running various parts of Freesound. It would be good to split them up into multiple files. I for example noticed today that ipython is in the requirements, but I would be very surprised if the production version of freesound needs ipython. So, the easiest way to do this is:

requirements-dev.txt:
```
-r requirements-production.txt  # this includes another file
dev
reqs
in
here
```

requirements-production.txt
```
requirements
for
production
in
here
```

On top of that it would be very good to pin the required package numbers. Having them not set is generally considered bad rather practice as things can be different between your different environments.

**Comment by bdejong** [comment]
( I saw that there are already splits for processing and similarity, but one does not negate the other. )

**Comment by alastair** [comment]
We discussed this briefly in chat too, coming to basically the same conclusion:
alastair> I've started using 2 requrements files
￼alastair> one for application dependencies, and one for development dependencies
￼alastair> we could do that in fs too
frederic> we need [ipython] for shell_plus, but I thought it was already installed as a dependency of that so I'm not sure why is in there
frederic> ￼maybe once we move to docker we can reorganise requeriments
￼frederic> for now I'd just add the version

**Comment by alastair** [comment]
It's worth noting that if we have pip >= 9.0.1 installed, it will correctly download the correct version of ipython for our version of python (in this case ipy 5.x for py 2.7)

**Comment by bdejong** [comment]
Looks like the travis yml needs `pip install -U pip` in there so it gets the latest pip before building/running...

**Comment by ffont** [comment]
Closing as this becomes kind of invalid after merging the Docker PR https://github.com/MTG/freesound/pull/1413
