### ISSUE TITLE
HTTP referrer policy

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#860]
As reported by a user using the support/contact form:

I'm seeing the long error message shown below when I try to log in because this website hasn't specified an explicit HTTP |referrer-policy| header and is relying on the default referrer policy to be |referrer-policy: no-referrer-when-downgrade|.

As of Firefox 53, users can change the default referrer policy via an about:config preference called network.http.referer.userControlPolicy to enhance user privacy. However, when this is set to 0 (i.e, "no-referrer"), it's not possible to log into Freesound. Please fix!

The error message:

"Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests."

**Comment by ffont** [comment]
Related to #574

**Comment by alastair** [comment]
It seems that this might not be possible to fix - 
see https://docs.djangoproject.com/en/2.0/ref/csrf/#how-it-works under the section "Removing the Referer header"

I don't think we'll able to do csrf under https with Referrer-policy: no-referrer.

We can specify our own policy in Freesound, but if a user manually overwrites it then we won't be able to guarantee that they can sign in.

**Comment by alastair** [comment]
Ah, although just reading the ticket again it appears that the Firefox setting is the default if this value is not already set, in that case then just setting one in nginx should be enough. I'll look into that and see if this fixes the issue

**Comment by alastair** [comment]
I've set nginx to return `Referrer-Policy: no-referrer-when-downgrade` in headers, which is the Firefox default and will override any user-set defaults. Firefox can log in even with the `network.http.referer.userControlPolicy` preference set to 0
