### ISSUE TITLE
Disable email sending to users whose addresses bounce, and inform them

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#884]
We can now receive notifications from our mail provider telling us if an email address that we are delivering to has bounced. We should use these notifications to make sure that we don't keep sending emails to accounts that can't receive email.

* If the email was an activation email, the account can never be used, delete the account.
* If it was any other email, mark the user who has this email as "email invalid"
* When sending emails, check if the user's email is marked as invalid, and if so, skip it.
* If a user logs in and has an invalid email, require them to change their email address to reactivate their account

**Comment by alastair** [comment]
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#bounce-object

**Comment by philtgun** [comment]
- [ ] db change: add invalid email field 
- [ ] django management command to use AWS API to get bounced emails and set flags (will be run periodically)
- [ ] cleanup script that removes unactivated users with invalid emails
- [ ] code checks for invalid email before sending and notify user with the middleware once he logins

**Comment by philtgun** [comment]
Related to removing unactivated users with invalid emails - do we remove unactivated users after certain timeout? If not, should we? @alastair @ffont

**Comment by alastair** [comment]
No, we don't automatically remove unactivated users, but we can add this.  We mark spammy users as inactive while they are in moderation, and so we don't want to delete all of them.

**Comment by philtgun** [comment]
Two things to adress:
- [ ] Amazon returns punycode email domains, they should be processed properly
- [ ] Need to add potion to save bounce data for possible processing and analytics

**Comment by ffont** [comment]
Closing this issue as it has been merged (https://github.com/MTG/freesound/pull/1189) and deployed
