### ISSUE TITLE
Site-wide notification system

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#885]
Sometimes we might want to send a message to all users. We could do this with a message bar at the top of each page.
Each page load can check a cache value, and if it is set, show the banner. A management command or fab command can be used to set and clear this value.

**Comment by andrebola** [comment]
We already implemented the banner used for the survey which is shown to all users for a specific period of time, I understand that this new message is going to be only shown once to each user.

I was planning to use django messages system to display it, so in that case we won't display a banner but a regular message box like this:

<img width="1100" alt="captura de pantalla 2017-06-26 a la s 12 17 18" src="https://user-images.githubusercontent.com/991305/27546593-9a5282c0-5a69-11e7-8fb6-763512bb0417.png">

So, if we only want to show this new message only once I think we should store in the DB for each user if we already did it or not.

**Comment by ffont** [comment]
I'm not sure if this is what @alastair meant when opening this issue. I think this came after a discussion with @bdejong in which we said that we should have a way to add site-wide message which would be always shown to all users and which could be dynamically changed without the need of deploying code (or even editing DB?). It would be some kind of banner whose contents we can change dynamically. I can't remember now the particular use case which was discussed, maybe with such a use case we can better define what it should be. Anyway, I don't think there is a need to remember to which users it has been shown and to which users has not. We always show it.

**Comment by andrebola** [comment]
OK, in that case we could change the banner that we have to take the text from the cache?

**Comment by ffont** [comment]
For the new UI we don't have a solution for that, we should add one.
