### ISSUE TITLE
Add logging of API access domain and http/s status

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#902]
We have configured our load balancer to redirect www.freesound.org to freesound.org, unless the URL is for `/apiv2` (https://github.com/MTG/freesound/issues/664).
We would love to redirect this for everything, but it causes issues with POST requests to the API. We want to see how many requests to the API are made to www and how many are made to no-www, grouped by api client. We can add these fields to the messages sent to graylog.
Once we have this data, we can work out the best approach to try and get all API clients to connect with no-www.

**Comment by alastair** [comment]
The second part of this issue should be to make a decision about how to contact api users and get them to change.

We should try and contact all API client users to get them to change the access domain to freesound.org without www. However, if there is released software actively being used by users which accesses www, it's likely that we can never add this redirect in place (unless we decide that we want to break the site for x% of users)

**Comment by ffont** [comment]
Reopening this issue as we only added logging for the protocol (http/https), but not for the domain (www/non-www).
