### ISSUE TITLE
Prepare Freesound development setup for implementing new front end

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#915]
We want to be able to start working on the new front end (which will be implemented from scratch) and be able to switch from the new front end to the other with a GET parameter (or some variable stored in DB on a user basis or something). The goal of this is that we can start updating the front end page by page. Just to provide some more context, we want to have the backend compatible with the two versions of the front end. We also thought of taking this opportunity to try using a different templating system like jinja. Some things to try/think/make decisions:

- How to specify which frontend to use (GET param?, session param?). I guess we basically need a middleware which sets a variable which is accessible then from the views.
- How make views choose one frontend or another? Maybe wrapper around the `render` function? In some cases it might happen that the view needs to redirect to some other view for the new frontend. 
- It can also happen that one frontend requires variables which another one does not. How to handle these cases? I guess if we have this middleware we can do if-elses for the backend type. Nevertheless the goal is to avoid that as much as possible, and have the two frontends share the same backend.
- The new frontend will most probably use some customised version of libraries like bootstrap or semantic-ui and we'll need to do some css pre-compiling. We should include this in the workflow somehow. We should see which is the best way to do integrate css/js/whatever pre-compilers with Django.

**Comment by andrebola** [comment]
Django supports multiple template engines, and it can be specified which to use by a name. This name is specified in the settings: https://github.com/MTG/freesound/blob/f22640188eb80cabc31d4b8a8cacfa51e569f5c0/freesound/settings.py#L334-L355

By defining our own render method we pass the name of the template engine to use:
https://github.com/MTG/freesound/blob/c7c98b552487a54148315d5a1e7757305bf9f54a/freesound/render.py#L1-L10

By doing it in this way we can decide later if we want to use django template engine or jinja2 and the only thing to change is the setting: 
https://github.com/MTG/freesound/blob/f22640188eb80cabc31d4b8a8cacfa51e569f5c0/freesound/settings.py#L337

Also note currently I created the folder templates2 for the new interface but this could be changed to use a template folder inside each app.

**Comment by bdejong** [comment]
@andrebola switching the templates might not be enough though: we also need to be able to switch the view functions... I guess you could do some crazy stuff with middleware and try to dynamically switch from one view to another.. I.e. define

```python
def my_view_function(...):
     return bleep

def my_view_function_newdesign(...):
    return bloop
```

and dynamically choose if you want to use my_view_function or my_view_function_newdesign?

**Comment by bdejong** [comment]
I guess you could put a dispatcher in front of views...

```python
def myview(request, ...):
   return "Something"
```

becomes

```python
def myview_new(request, ...):
   return "Something New!"

def myview(request, ...):
   if request.GET.get("newview", None) == "on":
       return my_new_view(request, ...)

   return "Something"
```

Heck you could even do that with a decorator :-)

```python
@dispatch_to_new(myview_new)
def myview(request, ...):
   return "Something"
```

and do the check in the decorator...

**Comment by andrebola** [comment]
Yes, I forgot to mention that. I think we have two options: 
1) try to separate the code of the backend for the two interfaces
2) try to have as much common code in the backend as we can, that means for example passing information from the views to the templates that will only be used in one of the templates and not in the other.

The first option have the advantage that when we want to completely remove the old interface will be very easy just to remove the old code, but the disadvantage is that we will have all the code duplicated (big files with code) and if we fix a bug in the old code then we have to also change manually the new code.

I prefer the second option since the logic in most cases will be the same. But there might be some case where we will need to have separated views, for example when a common code for the two templates would have a big impact in the performance. In those cases I would go for a solution like the one you mentioned, with the only difference of using the session variable:

```python
def myview_new(request, ...):
   return "Something New!"

def myview(request, ...):
   if request.session.get('new_frontend', False): 
       return my_new_view(request, ...)

   return "Something"
```

**Comment by ffont** [comment]
Regarding the pre-compiler workflow and the library we use, I think we should for the option of using a  javascript bundler like Gulp, in this way we have more flexibility afterwards. Regardless of the library we use, I think it will be good if we write our own css using something like sass. As for the library, I think we probably want to use wither Bootstrap or Semantic UI for their grid system, but other than that we'll probably have a lot of custom buttons and interactions. It will probably be easier to design our components from scratch than to customise some of the existing components in libraries (I'm not sure). However there are things we should definitely use like the grids. I'll ask some people about their opinion in which library should we use and let you know. However you could already setup some flow that uses Gulp to compile sass into css. The blog post you linked to seems to have a nice example.

Regarding the views case I also think like @andrebola that we should share the code as much as possible. In most of the cases it will be the same, but new interface might require somethings that old does not have and viceversa. Using `if else`'s based on a session variable is ok, but in any case we really need to be sure that we somehow "mark" the code which is needed for each version. The idea being that when we are finally able to get rid of old version we also get rid of unneeded code. Maybe we could mix both ideas. In views which change a lot we might want to have a decorator which dispatches different functions according to the selected frontend. In some other views we just need simple  `if else`'s for some variables or to add a redirect. We can provide an util function for that so we do `if is_new_frontend():`. In some other views the code might be the same for both interfaces, only changing the template chosen in the render method.

Regarding the templates to chose I'm not sure I understand your code example @andrebola. In https://github.com/MTG/freesound/issues/915#L5, isn't the `template_name` variable the one that should be changed? In any case I agree all templates for the new frontend should be in a different folder. We could separate them into an application per folder (as in modern django projects), but I think that might be a bit messy now. I'd do some sort of `new_templates` folder and in the future we can separate in apps if we want. In fact, would it make sense make a folder called `new_frontend` and use it to put the new templates and also the sass files and things that need to be precompiled? (in the future we rename to simply `frontend`).

I think we can stick with the Django template rendering engine, no need to change that.

**Comment by andrebola** [comment]
@ffont no, the trick is done by the last parameter of the method 'render_to_string'. That parameter specifies the name of the template configuration to use, which will be 'old_frontend' by default (specified in https://github.com/MTG/freesound/issues/915#L334).

The render function receives 'template_name' which will be for example 'sounds/sound.html' and that would be the same for both frontends, so if the file is not present in new_frontend templates folder it will be used the file in old_frontend folder. 

Note that the only thing that we need to change is the import of the render method that we are currently using for this custom render method.

**Comment by bdejong** [comment]
PS: none of what you guys are talking about it incompatible with what I'm saying... Creating a decorator could nicely hide the implementation details and simplify the cleanup afterwards...

```python
def new_view(request, blah):
   ...

@redirect_to_new(new_view)
def old_view(request, blah):
   ...
```

if infinitely nicer than:
```python
def new_view(request, blah):
   ...

def old_view(request, blah):
   if should_redirect(request):
      return new_view(request, blah)
   ...
```

**Comment by ffont** [comment]
sure, I think we could combine the approaches. we can have a utils file with a number if useful decorators and functions, this will make the code cleaning afterwards easier.

**Comment by ffont** [comment]
fyi, Giuseppe proposed to use webpack instead of gulp. we can look at the good sounds project setup as it was similar.
