### ISSUE TITLE
Update API docs to remove HTTPs examples and www examples

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#929]
API docs currently include examples using base URIs with `http` and `www` domain. We should update all examples to use `https` and non-www. Similarly we should check our API clients and update them to use `https` and non-www.

**Comment by bdejong** [comment]
https://github.com/MTG/freesound/search?p=1&q=%22www.freesound%22&type=&utf8=%E2%9C%93

There are some more details that point to www.freesound - might just fix them all at once...
