### ISSUE TITLE
Crazy amounts of spam in "personal description" fields

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#935]
http://freesound.org/forum/freesound-project/40305/

maybe we should not be showing the description of people until they download at least one sounds?
these guys are all using freesound as nice spam platform...

**Comment by andrebola** [comment]
I was planning to check the number of downloads before showing the description of the user but there is no reference to the the number of downloads of a user, so if I make the query it could be too heavy. 

I think we should add the field to the user and update it in the signal that counts the downloads for a sound: https://github.com/MTG/freesound/blob/master/sounds/models.py#L1087
But should we also count the downloads of packs?

**Comment by bdejong** [comment]
Perhaps cross-reference with #952 ? it's somewhat related...

**Comment by ffont** [comment]
Let's count both of them (packs and downloads), I think it makes sense.

**Comment by andrebola** [comment]
Ok, then this issue should be done after #1055
