### ISSUE TITLE
Make ratings non-generic foreign key

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#958]
Ratings have a generic foreign key, but we only use them for sounds. To simplify the database we should change them to be linked directly to sounds.

As a second thing we could consider, currently ratings are presented as 1-5 but are stored as 2× that value due to historical FS1 stuff. We could consider changing this underlying value to simplify the data that we store.

**Comment by bdejong** [comment]
Or.... add the possibility to rate packs?

**Comment by alastair** [comment]
either or :)
