### ISSUE TITLE
Some /apiv2 urls are browser-based and should therefore have www-nowww redirect

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#961]
We have a redirect for all pages from www.freesound.org to freesound.org, except on the `/apiv2/` path. This is so that we don't send redirects to any API clients (especially when doing `POST` during oauth).

Some pages under `/apiv2/apply` are meant to be accessed in a browser, and so we have the following situation:
1. User visits https://www.freesound.org/apiv2/apply
2. Because of our redirect exception rule, the user is not redirected to nowww
3. Because of the redirect, no user is logged in to www.freesound.org any more (no cookies); they are redirected to https://www.freesound.org/login?next=apiv2/apply
4. This isn't under apiv2, the redirect is triggered to https://freesound.org/login?next=apiv2/apply
5. Because the user is logged in, the [`login_redirect` decorator](https://github.com/MTG/freesound/blob/91841a86f79eb3b3e576334300dc4b5a60b5c01d/utils/session_checks.py#L27) sends the user to `/home` instead of the api apply page.

There are two solutions to this
1. Adjust the login view to redirect the user if they are logged in and `?next=` is set (done in #959)
2. Change the haproxy redirect to redirect www-nowww under `/apiv2/apply` too.

My preference is 2.

**Comment by bdejong** [comment]
Related question: what URL are we directing people to in the oauth flow? www or non-www?

**Comment by ffont** [comment]
We're not redirecting, so it depends on whether their original request was www or non-www.
All pages under the /apiv2 domain are not affected by the www/non-www and http/https redirects (although from now on /apiv2/apply will be an exception).

**Comment by alastair** [comment]
Currently the documentation uses www. everywhere (e.g. http://freesound.org/docs/api/authentication.html#oauth2-authentication) but we will update this (#929) so that from now on new clients will start connecting to non-www.

**Comment by alastair** [comment]
Fixed in the load balancer configuration
