### ISSUE TITLE
Use @transaction.atomic() where required

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#967]
During the last months we've fixed some "violates unique constraint" errors which happen because requests that access the DB *more than once* are not done in a single transaction. In such situations, it can happen that two requests that are processed simultaneously (e.g. if users double-click on a submit form) cause problems. Some of this errors have been reported and fixed:

 * Add ratings: issue https://github.com/MTG/freesound/issues/818, pr https://github.com/MTG/freesound/pull/939
 * Edit tags: issue https://github.com/MTG/freesound/issues/812, pr https://github.com/MTG/freesound/pull/942
 * Create new user: issue https://github.com/MTG/freesound/issues/742, pr https://github.com/MTG/freesound/pull/944

There are also very old tickets that might be related:
 * Duplicate md5: https://github.com/MTG/freesound/issues/389

We should go through all our views and evaluate whether or not we should wrap them into `@transaction.atomic()`decorators (or find other solutions like in https://github.com/MTG/freesound/issues/894, with the use of [F-expressions](https://docs.djangoproject.com/en/dev/ref/models/expressions/#f-expressions)).

**Comment by alastair** [comment]
Further to this, we are considering disabling buttons on form submit to prevent double-clicks, as the transaction protection won't prevent this error especially if we don't have a unique index on the thing that we create. More thoughts at https://github.com/MTG/freesound/pull/947#issuecomment-337842036
