### ISSUE TITLE
Improve speed of solr sound indexing

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#988]
The `manage.py reindex_solr` command sends data about all sounds to solr, however this process takes a long time. The biggest bottleneck is due to many queries being made to the database for each sound.

It looks like we tried to reduce the number of queries by using `select_related`, but we still need 2-3 queries per sound. Ideally we would do just one query for each block of sounds (default 4000).
We could use something like `bulk_query` in the `Sound` manager, but there are a number of fields which we need in solr that aren't needed in a normal sound display. For performance reasons, we shouldn't query these extra fields in a normal sound display so perhaps we need a variation of `bulk_query` for solr too.

**Comment by andrebola** [comment]
I started to work on this, using bulk_query with 4000 sounds takes around 30 seconds to index each block of sounds in my local. So it takes around 50 minutes to index all the sounds.
